// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal_server.proto

package io.littlehorse.common.proto;

/**
 * Protobuf type {@code littlehorse.CentralStoreQueryPb}
 */
public final class CentralStoreQueryPb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:littlehorse.CentralStoreQueryPb)
    CentralStoreQueryPbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CentralStoreQueryPb.newBuilder() to construct.
  private CentralStoreQueryPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CentralStoreQueryPb() {
    store_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CentralStoreQueryPb();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.littlehorse.common.proto.InternalServer.internal_static_littlehorse_CentralStoreQueryPb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.littlehorse.common.proto.InternalServer.internal_static_littlehorse_CentralStoreQueryPb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.littlehorse.common.proto.CentralStoreQueryPb.class, io.littlehorse.common.proto.CentralStoreQueryPb.Builder.class);
  }

  public interface CentralStoreSubQueryPbOrBuilder extends
      // @@protoc_insertion_point(interface_extends:littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     * @return Whether the key field is set.
     */
    boolean hasKey();
    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string last_from_prefix = 2;</code>
     * @return Whether the lastFromPrefix field is set.
     */
    boolean hasLastFromPrefix();
    /**
     * <code>string last_from_prefix = 2;</code>
     * @return The lastFromPrefix.
     */
    java.lang.String getLastFromPrefix();
    /**
     * <code>string last_from_prefix = 2;</code>
     * @return The bytes for lastFromPrefix.
     */
    com.google.protobuf.ByteString
        getLastFromPrefixBytes();

    io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.QueryCase getQueryCase();
  }
  /**
   * Protobuf type {@code littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb}
   */
  public static final class CentralStoreSubQueryPb extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb)
      CentralStoreSubQueryPbOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CentralStoreSubQueryPb.newBuilder() to construct.
    private CentralStoreSubQueryPb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CentralStoreSubQueryPb() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CentralStoreSubQueryPb();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.littlehorse.common.proto.InternalServer.internal_static_littlehorse_CentralStoreQueryPb_CentralStoreSubQueryPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.littlehorse.common.proto.InternalServer.internal_static_littlehorse_CentralStoreQueryPb_CentralStoreSubQueryPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.class, io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.Builder.class);
    }

    private int queryCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object query_;
    public enum QueryCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      KEY(1),
      LAST_FROM_PREFIX(2),
      QUERY_NOT_SET(0);
      private final int value;
      private QueryCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static QueryCase valueOf(int value) {
        return forNumber(value);
      }

      public static QueryCase forNumber(int value) {
        switch (value) {
          case 1: return KEY;
          case 2: return LAST_FROM_PREFIX;
          case 0: return QUERY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public QueryCase
    getQueryCase() {
      return QueryCase.forNumber(
          queryCase_);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    /**
     * <code>string key = 1;</code>
     * @return Whether the key field is set.
     */
    public boolean hasKey() {
      return queryCase_ == 1;
    }
    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = "";
      if (queryCase_ == 1) {
        ref = query_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (queryCase_ == 1) {
          query_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = "";
      if (queryCase_ == 1) {
        ref = query_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (queryCase_ == 1) {
          query_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_FROM_PREFIX_FIELD_NUMBER = 2;
    /**
     * <code>string last_from_prefix = 2;</code>
     * @return Whether the lastFromPrefix field is set.
     */
    public boolean hasLastFromPrefix() {
      return queryCase_ == 2;
    }
    /**
     * <code>string last_from_prefix = 2;</code>
     * @return The lastFromPrefix.
     */
    public java.lang.String getLastFromPrefix() {
      java.lang.Object ref = "";
      if (queryCase_ == 2) {
        ref = query_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (queryCase_ == 2) {
          query_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string last_from_prefix = 2;</code>
     * @return The bytes for lastFromPrefix.
     */
    public com.google.protobuf.ByteString
        getLastFromPrefixBytes() {
      java.lang.Object ref = "";
      if (queryCase_ == 2) {
        ref = query_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (queryCase_ == 2) {
          query_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (queryCase_ == 1) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, query_);
      }
      if (queryCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, query_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (queryCase_ == 1) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, query_);
      }
      if (queryCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, query_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb)) {
        return super.equals(obj);
      }
      io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb other = (io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb) obj;

      if (!getQueryCase().equals(other.getQueryCase())) return false;
      switch (queryCase_) {
        case 1:
          if (!getKey()
              .equals(other.getKey())) return false;
          break;
        case 2:
          if (!getLastFromPrefix()
              .equals(other.getLastFromPrefix())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (queryCase_) {
        case 1:
          hash = (37 * hash) + KEY_FIELD_NUMBER;
          hash = (53 * hash) + getKey().hashCode();
          break;
        case 2:
          hash = (37 * hash) + LAST_FROM_PREFIX_FIELD_NUMBER;
          hash = (53 * hash) + getLastFromPrefix().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb)
        io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.littlehorse.common.proto.InternalServer.internal_static_littlehorse_CentralStoreQueryPb_CentralStoreSubQueryPb_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.littlehorse.common.proto.InternalServer.internal_static_littlehorse_CentralStoreQueryPb_CentralStoreSubQueryPb_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.class, io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.Builder.class);
      }

      // Construct using io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        queryCase_ = 0;
        query_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.littlehorse.common.proto.InternalServer.internal_static_littlehorse_CentralStoreQueryPb_CentralStoreSubQueryPb_descriptor;
      }

      @java.lang.Override
      public io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb getDefaultInstanceForType() {
        return io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.getDefaultInstance();
      }

      @java.lang.Override
      public io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb build() {
        io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb buildPartial() {
        io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb result = new io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb result) {
        result.queryCase_ = queryCase_;
        result.query_ = this.query_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb) {
          return mergeFrom((io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb other) {
        if (other == io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.getDefaultInstance()) return this;
        switch (other.getQueryCase()) {
          case KEY: {
            queryCase_ = 1;
            query_ = other.query_;
            onChanged();
            break;
          }
          case LAST_FROM_PREFIX: {
            queryCase_ = 2;
            query_ = other.query_;
            onChanged();
            break;
          }
          case QUERY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                queryCase_ = 1;
                query_ = s;
                break;
              } // case 10
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                queryCase_ = 2;
                query_ = s;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int queryCase_ = 0;
      private java.lang.Object query_;
      public QueryCase
          getQueryCase() {
        return QueryCase.forNumber(
            queryCase_);
      }

      public Builder clearQuery() {
        queryCase_ = 0;
        query_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      /**
       * <code>string key = 1;</code>
       * @return Whether the key field is set.
       */
      @java.lang.Override
      public boolean hasKey() {
        return queryCase_ == 1;
      }
      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      @java.lang.Override
      public java.lang.String getKey() {
        java.lang.Object ref = "";
        if (queryCase_ == 1) {
          ref = query_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (queryCase_ == 1) {
            query_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = "";
        if (queryCase_ == 1) {
          ref = query_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (queryCase_ == 1) {
            query_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        queryCase_ = 1;
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        if (queryCase_ == 1) {
          queryCase_ = 0;
          query_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        queryCase_ = 1;
        query_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string last_from_prefix = 2;</code>
       * @return Whether the lastFromPrefix field is set.
       */
      @java.lang.Override
      public boolean hasLastFromPrefix() {
        return queryCase_ == 2;
      }
      /**
       * <code>string last_from_prefix = 2;</code>
       * @return The lastFromPrefix.
       */
      @java.lang.Override
      public java.lang.String getLastFromPrefix() {
        java.lang.Object ref = "";
        if (queryCase_ == 2) {
          ref = query_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (queryCase_ == 2) {
            query_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string last_from_prefix = 2;</code>
       * @return The bytes for lastFromPrefix.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLastFromPrefixBytes() {
        java.lang.Object ref = "";
        if (queryCase_ == 2) {
          ref = query_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (queryCase_ == 2) {
            query_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string last_from_prefix = 2;</code>
       * @param value The lastFromPrefix to set.
       * @return This builder for chaining.
       */
      public Builder setLastFromPrefix(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        queryCase_ = 2;
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string last_from_prefix = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastFromPrefix() {
        if (queryCase_ == 2) {
          queryCase_ = 0;
          query_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string last_from_prefix = 2;</code>
       * @param value The bytes for lastFromPrefix to set.
       * @return This builder for chaining.
       */
      public Builder setLastFromPrefixBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        queryCase_ = 2;
        query_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb)
    }

    // @@protoc_insertion_point(class_scope:littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb)
    private static final io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb();
    }

    public static io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CentralStoreSubQueryPb>
        PARSER = new com.google.protobuf.AbstractParser<CentralStoreSubQueryPb>() {
      @java.lang.Override
      public CentralStoreSubQueryPb parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CentralStoreSubQueryPb> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CentralStoreSubQueryPb> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int ENABLE_STALE_STORES_FIELD_NUMBER = 1;
  private boolean enableStaleStores_ = false;
  /**
   * <code>bool enable_stale_stores = 1;</code>
   * @return The enableStaleStores.
   */
  @java.lang.Override
  public boolean getEnableStaleStores() {
    return enableStaleStores_;
  }

  public static final int SPECIFIC_PARTITION_FIELD_NUMBER = 2;
  private int specificPartition_ = 0;
  /**
   * <code>optional int32 specific_partition = 2;</code>
   * @return Whether the specificPartition field is set.
   */
  @java.lang.Override
  public boolean hasSpecificPartition() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 specific_partition = 2;</code>
   * @return The specificPartition.
   */
  @java.lang.Override
  public int getSpecificPartition() {
    return specificPartition_;
  }

  public static final int QUERY_FIELD_NUMBER = 3;
  private io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb query_;
  /**
   * <code>.littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb query = 3;</code>
   * @return Whether the query field is set.
   */
  @java.lang.Override
  public boolean hasQuery() {
    return query_ != null;
  }
  /**
   * <code>.littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb query = 3;</code>
   * @return The query.
   */
  @java.lang.Override
  public io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb getQuery() {
    return query_ == null ? io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.getDefaultInstance() : query_;
  }
  /**
   * <code>.littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb query = 3;</code>
   */
  @java.lang.Override
  public io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPbOrBuilder getQueryOrBuilder() {
    return query_ == null ? io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.getDefaultInstance() : query_;
  }

  public static final int STORE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object store_ = "";
  /**
   * <code>string store = 4;</code>
   * @return The store.
   */
  @java.lang.Override
  public java.lang.String getStore() {
    java.lang.Object ref = store_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      store_ = s;
      return s;
    }
  }
  /**
   * <code>string store = 4;</code>
   * @return The bytes for store.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStoreBytes() {
    java.lang.Object ref = store_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      store_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (enableStaleStores_ != false) {
      output.writeBool(1, enableStaleStores_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(2, specificPartition_);
    }
    if (query_ != null) {
      output.writeMessage(3, getQuery());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(store_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, store_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (enableStaleStores_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, enableStaleStores_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, specificPartition_);
    }
    if (query_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getQuery());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(store_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, store_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.littlehorse.common.proto.CentralStoreQueryPb)) {
      return super.equals(obj);
    }
    io.littlehorse.common.proto.CentralStoreQueryPb other = (io.littlehorse.common.proto.CentralStoreQueryPb) obj;

    if (getEnableStaleStores()
        != other.getEnableStaleStores()) return false;
    if (hasSpecificPartition() != other.hasSpecificPartition()) return false;
    if (hasSpecificPartition()) {
      if (getSpecificPartition()
          != other.getSpecificPartition()) return false;
    }
    if (hasQuery() != other.hasQuery()) return false;
    if (hasQuery()) {
      if (!getQuery()
          .equals(other.getQuery())) return false;
    }
    if (!getStore()
        .equals(other.getStore())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENABLE_STALE_STORES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEnableStaleStores());
    if (hasSpecificPartition()) {
      hash = (37 * hash) + SPECIFIC_PARTITION_FIELD_NUMBER;
      hash = (53 * hash) + getSpecificPartition();
    }
    if (hasQuery()) {
      hash = (37 * hash) + QUERY_FIELD_NUMBER;
      hash = (53 * hash) + getQuery().hashCode();
    }
    hash = (37 * hash) + STORE_FIELD_NUMBER;
    hash = (53 * hash) + getStore().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.littlehorse.common.proto.CentralStoreQueryPb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.common.proto.CentralStoreQueryPb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.common.proto.CentralStoreQueryPb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.common.proto.CentralStoreQueryPb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.common.proto.CentralStoreQueryPb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.common.proto.CentralStoreQueryPb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.common.proto.CentralStoreQueryPb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.common.proto.CentralStoreQueryPb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.littlehorse.common.proto.CentralStoreQueryPb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.littlehorse.common.proto.CentralStoreQueryPb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.common.proto.CentralStoreQueryPb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.common.proto.CentralStoreQueryPb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.littlehorse.common.proto.CentralStoreQueryPb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code littlehorse.CentralStoreQueryPb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:littlehorse.CentralStoreQueryPb)
      io.littlehorse.common.proto.CentralStoreQueryPbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.littlehorse.common.proto.InternalServer.internal_static_littlehorse_CentralStoreQueryPb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.littlehorse.common.proto.InternalServer.internal_static_littlehorse_CentralStoreQueryPb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.littlehorse.common.proto.CentralStoreQueryPb.class, io.littlehorse.common.proto.CentralStoreQueryPb.Builder.class);
    }

    // Construct using io.littlehorse.common.proto.CentralStoreQueryPb.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      enableStaleStores_ = false;
      specificPartition_ = 0;
      query_ = null;
      if (queryBuilder_ != null) {
        queryBuilder_.dispose();
        queryBuilder_ = null;
      }
      store_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.littlehorse.common.proto.InternalServer.internal_static_littlehorse_CentralStoreQueryPb_descriptor;
    }

    @java.lang.Override
    public io.littlehorse.common.proto.CentralStoreQueryPb getDefaultInstanceForType() {
      return io.littlehorse.common.proto.CentralStoreQueryPb.getDefaultInstance();
    }

    @java.lang.Override
    public io.littlehorse.common.proto.CentralStoreQueryPb build() {
      io.littlehorse.common.proto.CentralStoreQueryPb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.littlehorse.common.proto.CentralStoreQueryPb buildPartial() {
      io.littlehorse.common.proto.CentralStoreQueryPb result = new io.littlehorse.common.proto.CentralStoreQueryPb(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.littlehorse.common.proto.CentralStoreQueryPb result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.enableStaleStores_ = enableStaleStores_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.specificPartition_ = specificPartition_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.query_ = queryBuilder_ == null
            ? query_
            : queryBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.store_ = store_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.littlehorse.common.proto.CentralStoreQueryPb) {
        return mergeFrom((io.littlehorse.common.proto.CentralStoreQueryPb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.littlehorse.common.proto.CentralStoreQueryPb other) {
      if (other == io.littlehorse.common.proto.CentralStoreQueryPb.getDefaultInstance()) return this;
      if (other.getEnableStaleStores() != false) {
        setEnableStaleStores(other.getEnableStaleStores());
      }
      if (other.hasSpecificPartition()) {
        setSpecificPartition(other.getSpecificPartition());
      }
      if (other.hasQuery()) {
        mergeQuery(other.getQuery());
      }
      if (!other.getStore().isEmpty()) {
        store_ = other.store_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              enableStaleStores_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              specificPartition_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getQueryFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              store_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean enableStaleStores_ ;
    /**
     * <code>bool enable_stale_stores = 1;</code>
     * @return The enableStaleStores.
     */
    @java.lang.Override
    public boolean getEnableStaleStores() {
      return enableStaleStores_;
    }
    /**
     * <code>bool enable_stale_stores = 1;</code>
     * @param value The enableStaleStores to set.
     * @return This builder for chaining.
     */
    public Builder setEnableStaleStores(boolean value) {

      enableStaleStores_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool enable_stale_stores = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnableStaleStores() {
      bitField0_ = (bitField0_ & ~0x00000001);
      enableStaleStores_ = false;
      onChanged();
      return this;
    }

    private int specificPartition_ ;
    /**
     * <code>optional int32 specific_partition = 2;</code>
     * @return Whether the specificPartition field is set.
     */
    @java.lang.Override
    public boolean hasSpecificPartition() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 specific_partition = 2;</code>
     * @return The specificPartition.
     */
    @java.lang.Override
    public int getSpecificPartition() {
      return specificPartition_;
    }
    /**
     * <code>optional int32 specific_partition = 2;</code>
     * @param value The specificPartition to set.
     * @return This builder for chaining.
     */
    public Builder setSpecificPartition(int value) {

      specificPartition_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 specific_partition = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpecificPartition() {
      bitField0_ = (bitField0_ & ~0x00000002);
      specificPartition_ = 0;
      onChanged();
      return this;
    }

    private io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb query_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb, io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.Builder, io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPbOrBuilder> queryBuilder_;
    /**
     * <code>.littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb query = 3;</code>
     * @return Whether the query field is set.
     */
    public boolean hasQuery() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb query = 3;</code>
     * @return The query.
     */
    public io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb getQuery() {
      if (queryBuilder_ == null) {
        return query_ == null ? io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.getDefaultInstance() : query_;
      } else {
        return queryBuilder_.getMessage();
      }
    }
    /**
     * <code>.littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb query = 3;</code>
     */
    public Builder setQuery(io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb value) {
      if (queryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        query_ = value;
      } else {
        queryBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb query = 3;</code>
     */
    public Builder setQuery(
        io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.Builder builderForValue) {
      if (queryBuilder_ == null) {
        query_ = builderForValue.build();
      } else {
        queryBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb query = 3;</code>
     */
    public Builder mergeQuery(io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb value) {
      if (queryBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          query_ != null &&
          query_ != io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.getDefaultInstance()) {
          getQueryBuilder().mergeFrom(value);
        } else {
          query_ = value;
        }
      } else {
        queryBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb query = 3;</code>
     */
    public Builder clearQuery() {
      bitField0_ = (bitField0_ & ~0x00000004);
      query_ = null;
      if (queryBuilder_ != null) {
        queryBuilder_.dispose();
        queryBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb query = 3;</code>
     */
    public io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.Builder getQueryBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getQueryFieldBuilder().getBuilder();
    }
    /**
     * <code>.littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb query = 3;</code>
     */
    public io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPbOrBuilder getQueryOrBuilder() {
      if (queryBuilder_ != null) {
        return queryBuilder_.getMessageOrBuilder();
      } else {
        return query_ == null ?
            io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.getDefaultInstance() : query_;
      }
    }
    /**
     * <code>.littlehorse.CentralStoreQueryPb.CentralStoreSubQueryPb query = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb, io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.Builder, io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPbOrBuilder> 
        getQueryFieldBuilder() {
      if (queryBuilder_ == null) {
        queryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb, io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPb.Builder, io.littlehorse.common.proto.CentralStoreQueryPb.CentralStoreSubQueryPbOrBuilder>(
                getQuery(),
                getParentForChildren(),
                isClean());
        query_ = null;
      }
      return queryBuilder_;
    }

    private java.lang.Object store_ = "";
    /**
     * <code>string store = 4;</code>
     * @return The store.
     */
    public java.lang.String getStore() {
      java.lang.Object ref = store_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        store_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string store = 4;</code>
     * @return The bytes for store.
     */
    public com.google.protobuf.ByteString
        getStoreBytes() {
      java.lang.Object ref = store_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        store_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string store = 4;</code>
     * @param value The store to set.
     * @return This builder for chaining.
     */
    public Builder setStore(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      store_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string store = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStore() {
      store_ = getDefaultInstance().getStore();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string store = 4;</code>
     * @param value The bytes for store to set.
     * @return This builder for chaining.
     */
    public Builder setStoreBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      store_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:littlehorse.CentralStoreQueryPb)
  }

  // @@protoc_insertion_point(class_scope:littlehorse.CentralStoreQueryPb)
  private static final io.littlehorse.common.proto.CentralStoreQueryPb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.littlehorse.common.proto.CentralStoreQueryPb();
  }

  public static io.littlehorse.common.proto.CentralStoreQueryPb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CentralStoreQueryPb>
      PARSER = new com.google.protobuf.AbstractParser<CentralStoreQueryPb>() {
    @java.lang.Override
    public CentralStoreQueryPb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CentralStoreQueryPb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CentralStoreQueryPb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.littlehorse.common.proto.CentralStoreQueryPb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

