
[changelog]
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="scope") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - *{{ commit.group }}* \
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false

commit_parsers = [
  { message = "^feat", group = "Feature" },
  { message = "^fix", group = "Bug Fix" },
  { message = "^doc", group = "Documentation" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactor" },
  { message = "^style", group = "Styling" },
  { message = "^test", group = "Testing" },
  { message = "^chore|^ci", group = "Miscellaneous Task" },
  { body = ".*security", group = "Security" },
  { message = "^revert", group = "Revert" },
]

protect_breaking_commits = false
filter_commits = false
topo_order = false
sort_commits = "oldest"
