name: Build and publish docker images
description: Builds and publish docker images to github registry
inputs:
  github-token:
    description: Github secret secrets.GITHUB_TOKEN
    required: true
  image-name:
    description: Image name for example lh-server
    required: true
  context:
    description: Docker build context path
    default: .
  dockerfile:
    description: Relative route of Dockerfile
    required: true

runs:
  using: composite
  steps:
    - name: Log in to github registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository }}/${{ inputs.image-name }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
