// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package io.littlehorse.jlib.common.proto;

/**
 * Protobuf enum {@code littlehorse.ComparatorPb}
 */
public enum ComparatorPb
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LESS_THAN = 0;</code>
   */
  LESS_THAN(0),
  /**
   * <code>GREATER_THAN = 1;</code>
   */
  GREATER_THAN(1),
  /**
   * <code>LESS_THAN_EQ = 2;</code>
   */
  LESS_THAN_EQ(2),
  /**
   * <code>GREATER_THAN_EQ = 3;</code>
   */
  GREATER_THAN_EQ(3),
  /**
   * <code>EQUALS = 4;</code>
   */
  EQUALS(4),
  /**
   * <code>NOT_EQUALS = 5;</code>
   */
  NOT_EQUALS(5),
  /**
   * <code>IN = 6;</code>
   */
  IN(6),
  /**
   * <code>NOT_IN = 7;</code>
   */
  NOT_IN(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>LESS_THAN = 0;</code>
   */
  public static final int LESS_THAN_VALUE = 0;
  /**
   * <code>GREATER_THAN = 1;</code>
   */
  public static final int GREATER_THAN_VALUE = 1;
  /**
   * <code>LESS_THAN_EQ = 2;</code>
   */
  public static final int LESS_THAN_EQ_VALUE = 2;
  /**
   * <code>GREATER_THAN_EQ = 3;</code>
   */
  public static final int GREATER_THAN_EQ_VALUE = 3;
  /**
   * <code>EQUALS = 4;</code>
   */
  public static final int EQUALS_VALUE = 4;
  /**
   * <code>NOT_EQUALS = 5;</code>
   */
  public static final int NOT_EQUALS_VALUE = 5;
  /**
   * <code>IN = 6;</code>
   */
  public static final int IN_VALUE = 6;
  /**
   * <code>NOT_IN = 7;</code>
   */
  public static final int NOT_IN_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ComparatorPb valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ComparatorPb forNumber(int value) {
    switch (value) {
      case 0: return LESS_THAN;
      case 1: return GREATER_THAN;
      case 2: return LESS_THAN_EQ;
      case 3: return GREATER_THAN_EQ;
      case 4: return EQUALS;
      case 5: return NOT_EQUALS;
      case 6: return IN;
      case 7: return NOT_IN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ComparatorPb>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ComparatorPb> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ComparatorPb>() {
          public ComparatorPb findValueByNumber(int number) {
            return ComparatorPb.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.littlehorse.jlib.common.proto.Service.getDescriptor().getEnumTypes().get(6);
  }

  private static final ComparatorPb[] VALUES = values();

  public static ComparatorPb valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ComparatorPb(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:littlehorse.ComparatorPb)
}

