// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common_wfspec.proto

package io.littlehorse.sdk.common.proto;

public final class CommonWfspec {
  private CommonWfspec() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_VariableAssignment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_VariableAssignment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_VariableAssignment_FormatString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_VariableAssignment_FormatString_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_VariableAssignment_NodeOutputReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_VariableAssignment_NodeOutputReference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_VariableAssignment_Expression_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_VariableAssignment_Expression_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_VariableMutation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_VariableMutation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_VariableMutation_NodeOutputSource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_VariableMutation_NodeOutputSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_VariableDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_VariableDef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_TypeDefinition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_TypeDefinition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ReturnType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ReturnType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UTActionTrigger_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UTActionTrigger_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UTActionTrigger_UTACancel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UTActionTrigger_UTACancel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UTActionTrigger_UTATask_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UTActionTrigger_UTATask_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UTActionTrigger_UTAReassign_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UTActionTrigger_UTAReassign_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ExponentialBackoffRetryPolicy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_ExponentialBackoffRetryPolicy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_TaskNode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_TaskNode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023common_wfspec.proto\022\013littlehorse\032\022comm" +
      "on_enums.proto\032\016variable.proto\032\017object_i" +
      "d.proto\"\242\005\n\022VariableAssignment\022\026\n\tjson_p" +
      "ath\030\001 \001(\tH\001\210\001\001\022\027\n\rvariable_name\030\002 \001(\tH\000\022" +
      "3\n\rliteral_value\030\003 \001(\0132\032.littlehorse.Var" +
      "iableValueH\000\022E\n\rformat_string\030\004 \001(\0132,.li" +
      "ttlehorse.VariableAssignment.FormatStrin" +
      "gH\000\022J\n\013node_output\030\005 \001(\01323.littlehorse.V" +
      "ariableAssignment.NodeOutputReferenceH\000\022" +
      "@\n\nexpression\030\006 \001(\0132*.littlehorse.Variab" +
      "leAssignment.ExpressionH\000\032n\n\014FormatStrin" +
      "g\022/\n\006format\030\001 \001(\0132\037.littlehorse.Variable" +
      "Assignment\022-\n\004args\030\002 \003(\0132\037.littlehorse.V" +
      "ariableAssignment\032(\n\023NodeOutputReference" +
      "\022\021\n\tnode_name\030\001 \001(\t\032\236\001\n\nExpression\022,\n\003lh" +
      "s\030\001 \001(\0132\037.littlehorse.VariableAssignment" +
      "\0224\n\toperation\030\002 \001(\0162!.littlehorse.Variab" +
      "leMutationType\022,\n\003rhs\030\003 \001(\0132\037.littlehors" +
      "e.VariableAssignmentB\010\n\006sourceB\014\n\n_json_" +
      "path\"\204\003\n\020VariableMutation\022\020\n\010lhs_name\030\001 " +
      "\001(\t\022\032\n\rlhs_json_path\030\002 \001(\tH\001\210\001\001\0224\n\topera" +
      "tion\030\003 \001(\0162!.littlehorse.VariableMutatio" +
      "nType\0229\n\016rhs_assignment\030\004 \001(\0132\037.littleho" +
      "rse.VariableAssignmentH\000\0223\n\rliteral_valu" +
      "e\030\005 \001(\0132\032.littlehorse.VariableValueH\000\022E\n" +
      "\013node_output\030\006 \001(\0132..littlehorse.Variabl" +
      "eMutation.NodeOutputSourceH\000\0326\n\020NodeOutp" +
      "utSource\022\025\n\010jsonpath\030\n \001(\tH\000\210\001\001B\013\n\t_json" +
      "pathB\013\n\trhs_valueB\020\n\016_lhs_json_path\"\225\002\n\013" +
      "VariableDef\0226\n\016primitive_type\030\001 \001(\0162\031.li" +
      "ttlehorse.VariableTypeH\000\210\001\001\022\014\n\004name\030\002 \001(" +
      "\t\0226\n\rdefault_value\030\003 \001(\0132\032.littlehorse.V" +
      "ariableValueH\001\210\001\001\022\031\n\014masked_value\030\004 \001(\010H" +
      "\002\210\001\001\022.\n\004type\030\005 \001(\0132\033.littlehorse.TypeDef" +
      "initionH\003\210\001\001B\021\n\017_primitive_typeB\020\n\016_defa" +
      "ult_valueB\017\n\r_masked_valueB\007\n\005_type\"U\n\016T" +
      "ypeDefinition\022\'\n\004type\030\001 \001(\0162\031.littlehors" +
      "e.VariableType\022\016\n\006masked\030\004 \001(\010J\004\010\002\020\003J\004\010\003" +
      "\020\004\"S\n\nReturnType\0225\n\013return_type\030\001 \001(\0132\033." +
      "littlehorse.TypeDefinitionH\000\210\001\001B\016\n\014_retu" +
      "rn_type\"\357\004\n\017UTActionTrigger\0224\n\004task\030\001 \001(" +
      "\0132$.littlehorse.UTActionTrigger.UTATaskH" +
      "\000\0228\n\006cancel\030\002 \001(\0132&.littlehorse.UTAction" +
      "Trigger.UTACancelH\000\022<\n\010reassign\030\003 \001(\0132(." +
      "littlehorse.UTActionTrigger.UTAReassignH" +
      "\000\0226\n\rdelay_seconds\030\005 \001(\0132\037.littlehorse.V" +
      "ariableAssignment\0221\n\004hook\030\006 \001(\0162#.little" +
      "horse.UTActionTrigger.UTHook\032\013\n\tUTACance" +
      "l\032`\n\007UTATask\022#\n\004task\030\001 \001(\0132\025.littlehorse" +
      ".TaskNode\0220\n\tmutations\030\002 \003(\0132\035.littlehor" +
      "se.VariableMutation\032\231\001\n\013UTAReassign\0225\n\007u" +
      "ser_id\030\001 \001(\0132\037.littlehorse.VariableAssig" +
      "nmentH\000\210\001\001\0228\n\nuser_group\030\002 \001(\0132\037.littleh" +
      "orse.VariableAssignmentH\001\210\001\001B\n\n\010_user_id" +
      "B\r\n\013_user_group\".\n\006UTHook\022\016\n\nON_ARRIVAL\020" +
      "\000\022\024\n\020ON_TASK_ASSIGNED\020\001B\010\n\006action\"c\n\035Exp" +
      "onentialBackoffRetryPolicy\022\030\n\020base_inter" +
      "val_ms\030\001 \001(\005\022\024\n\014max_delay_ms\030\002 \001(\003\022\022\n\nmu" +
      "ltiplier\030\003 \001(\002\"\311\002\n\010TaskNode\022-\n\013task_def_" +
      "id\030\001 \001(\0132\026.littlehorse.TaskDefIdH\000\0227\n\014dy" +
      "namic_task\030\006 \001(\0132\037.littlehorse.VariableA" +
      "ssignmentH\000\022\027\n\017timeout_seconds\030\002 \001(\005\022\017\n\007" +
      "retries\030\003 \001(\005\022L\n\023exponential_backoff\030\005 \001" +
      "(\0132*.littlehorse.ExponentialBackoffRetry" +
      "PolicyH\001\210\001\001\0222\n\tvariables\030\004 \003(\0132\037.littleh" +
      "orse.VariableAssignmentB\021\n\017task_to_execu" +
      "teB\026\n\024_exponential_backoff*\230\001\n\024VariableM" +
      "utationType\022\n\n\006ASSIGN\020\000\022\007\n\003ADD\020\001\022\n\n\006EXTE" +
      "ND\020\002\022\014\n\010SUBTRACT\020\003\022\014\n\010MULTIPLY\020\004\022\n\n\006DIVI" +
      "DE\020\005\022\025\n\021REMOVE_IF_PRESENT\020\006\022\020\n\014REMOVE_IN" +
      "DEX\020\007\022\016\n\nREMOVE_KEY\020\010*\204\001\n\nComparator\022\r\n\t" +
      "LESS_THAN\020\000\022\020\n\014GREATER_THAN\020\001\022\020\n\014LESS_TH" +
      "AN_EQ\020\002\022\023\n\017GREATER_THAN_EQ\020\003\022\n\n\006EQUALS\020\004" +
      "\022\016\n\nNOT_EQUALS\020\005\022\006\n\002IN\020\006\022\n\n\006NOT_IN\020\007BM\n\037" +
      "io.littlehorse.sdk.common.protoP\001Z\t.;lhp" +
      "roto\252\002\034LittleHorse.Sdk.Common.Protob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.littlehorse.sdk.common.proto.CommonEnums.getDescriptor(),
          io.littlehorse.sdk.common.proto.VariableOuterClass.getDescriptor(),
          io.littlehorse.sdk.common.proto.ObjectId.getDescriptor(),
        });
    internal_static_littlehorse_VariableAssignment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_littlehorse_VariableAssignment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_VariableAssignment_descriptor,
        new java.lang.String[] { "JsonPath", "VariableName", "LiteralValue", "FormatString", "NodeOutput", "Expression", "Source", "JsonPath", });
    internal_static_littlehorse_VariableAssignment_FormatString_descriptor =
      internal_static_littlehorse_VariableAssignment_descriptor.getNestedTypes().get(0);
    internal_static_littlehorse_VariableAssignment_FormatString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_VariableAssignment_FormatString_descriptor,
        new java.lang.String[] { "Format", "Args", });
    internal_static_littlehorse_VariableAssignment_NodeOutputReference_descriptor =
      internal_static_littlehorse_VariableAssignment_descriptor.getNestedTypes().get(1);
    internal_static_littlehorse_VariableAssignment_NodeOutputReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_VariableAssignment_NodeOutputReference_descriptor,
        new java.lang.String[] { "NodeName", });
    internal_static_littlehorse_VariableAssignment_Expression_descriptor =
      internal_static_littlehorse_VariableAssignment_descriptor.getNestedTypes().get(2);
    internal_static_littlehorse_VariableAssignment_Expression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_VariableAssignment_Expression_descriptor,
        new java.lang.String[] { "Lhs", "Operation", "Rhs", });
    internal_static_littlehorse_VariableMutation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_littlehorse_VariableMutation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_VariableMutation_descriptor,
        new java.lang.String[] { "LhsName", "LhsJsonPath", "Operation", "RhsAssignment", "LiteralValue", "NodeOutput", "RhsValue", "LhsJsonPath", });
    internal_static_littlehorse_VariableMutation_NodeOutputSource_descriptor =
      internal_static_littlehorse_VariableMutation_descriptor.getNestedTypes().get(0);
    internal_static_littlehorse_VariableMutation_NodeOutputSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_VariableMutation_NodeOutputSource_descriptor,
        new java.lang.String[] { "Jsonpath", "Jsonpath", });
    internal_static_littlehorse_VariableDef_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_littlehorse_VariableDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_VariableDef_descriptor,
        new java.lang.String[] { "PrimitiveType", "Name", "DefaultValue", "MaskedValue", "Type", "PrimitiveType", "DefaultValue", "MaskedValue", "Type", });
    internal_static_littlehorse_TypeDefinition_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_littlehorse_TypeDefinition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_TypeDefinition_descriptor,
        new java.lang.String[] { "Type", "Masked", });
    internal_static_littlehorse_ReturnType_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_littlehorse_ReturnType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ReturnType_descriptor,
        new java.lang.String[] { "ReturnType", "ReturnType", });
    internal_static_littlehorse_UTActionTrigger_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_littlehorse_UTActionTrigger_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UTActionTrigger_descriptor,
        new java.lang.String[] { "Task", "Cancel", "Reassign", "DelaySeconds", "Hook", "Action", });
    internal_static_littlehorse_UTActionTrigger_UTACancel_descriptor =
      internal_static_littlehorse_UTActionTrigger_descriptor.getNestedTypes().get(0);
    internal_static_littlehorse_UTActionTrigger_UTACancel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UTActionTrigger_UTACancel_descriptor,
        new java.lang.String[] { });
    internal_static_littlehorse_UTActionTrigger_UTATask_descriptor =
      internal_static_littlehorse_UTActionTrigger_descriptor.getNestedTypes().get(1);
    internal_static_littlehorse_UTActionTrigger_UTATask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UTActionTrigger_UTATask_descriptor,
        new java.lang.String[] { "Task", "Mutations", });
    internal_static_littlehorse_UTActionTrigger_UTAReassign_descriptor =
      internal_static_littlehorse_UTActionTrigger_descriptor.getNestedTypes().get(2);
    internal_static_littlehorse_UTActionTrigger_UTAReassign_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UTActionTrigger_UTAReassign_descriptor,
        new java.lang.String[] { "UserId", "UserGroup", "UserId", "UserGroup", });
    internal_static_littlehorse_ExponentialBackoffRetryPolicy_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_littlehorse_ExponentialBackoffRetryPolicy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_ExponentialBackoffRetryPolicy_descriptor,
        new java.lang.String[] { "BaseIntervalMs", "MaxDelayMs", "Multiplier", });
    internal_static_littlehorse_TaskNode_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_littlehorse_TaskNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_TaskNode_descriptor,
        new java.lang.String[] { "TaskDefId", "DynamicTask", "TimeoutSeconds", "Retries", "ExponentialBackoff", "Variables", "TaskToExecute", "ExponentialBackoff", });
    io.littlehorse.sdk.common.proto.CommonEnums.getDescriptor();
    io.littlehorse.sdk.common.proto.VariableOuterClass.getDescriptor();
    io.littlehorse.sdk.common.proto.ObjectId.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
