// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package io.littlehorse.sdk.common.proto;

public interface DeleteStructDefRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.DeleteStructDefRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.littlehorse.StructDefId id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.littlehorse.StructDefId id = 1;</code>
   * @return The id.
   */
  io.littlehorse.sdk.common.proto.StructDefId getId();
  /**
   * <code>.littlehorse.StructDefId id = 1;</code>
   */
  io.littlehorse.sdk.common.proto.StructDefIdOrBuilder getIdOrBuilder();
}
