// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package io.littlehorse.sdk.common.proto;

public interface ListMetricRunRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.ListMetricRunRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.littlehorse.MetricId metric_id = 1;</code>
   * @return Whether the metricId field is set.
   */
  boolean hasMetricId();
  /**
   * <code>.littlehorse.MetricId metric_id = 1;</code>
   * @return The metricId.
   */
  io.littlehorse.sdk.common.proto.MetricId getMetricId();
  /**
   * <code>.littlehorse.MetricId metric_id = 1;</code>
   */
  io.littlehorse.sdk.common.proto.MetricIdOrBuilder getMetricIdOrBuilder();
}
