// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: acls.proto

package io.littlehorse.sdk.common.proto;

/**
 * <pre>
 * This is a GlobalGetable.
 * </pre>
 *
 * Protobuf type {@code littlehorse.Principal}
 */
public final class Principal extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:littlehorse.Principal)
    PrincipalOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Principal.newBuilder() to construct.
  private Principal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Principal() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Principal();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.littlehorse.sdk.common.proto.Acls.internal_static_littlehorse_Principal_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetPerTenantAcls();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.littlehorse.sdk.common.proto.Acls.internal_static_littlehorse_Principal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.littlehorse.sdk.common.proto.Principal.class, io.littlehorse.sdk.common.proto.Principal.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private io.littlehorse.sdk.common.proto.PrincipalId id_;
  /**
   * <pre>
   * Principals are agnostic of the Authentication protocol that you use. In OAuth,
   * the id is retrieved by looking at the claims on the request. In mTLS, the
   * id is retrived by looking at the Subject Name of the client certificate.
   * </pre>
   *
   * <code>.littlehorse.PrincipalId id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return id_ != null;
  }
  /**
   * <pre>
   * Principals are agnostic of the Authentication protocol that you use. In OAuth,
   * the id is retrieved by looking at the claims on the request. In mTLS, the
   * id is retrived by looking at the Subject Name of the client certificate.
   * </pre>
   *
   * <code>.littlehorse.PrincipalId id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.PrincipalId getId() {
    return id_ == null ? io.littlehorse.sdk.common.proto.PrincipalId.getDefaultInstance() : id_;
  }
  /**
   * <pre>
   * Principals are agnostic of the Authentication protocol that you use. In OAuth,
   * the id is retrieved by looking at the claims on the request. In mTLS, the
   * id is retrived by looking at the Subject Name of the client certificate.
   * </pre>
   *
   * <code>.littlehorse.PrincipalId id = 1;</code>
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.PrincipalIdOrBuilder getIdOrBuilder() {
    return id_ == null ? io.littlehorse.sdk.common.proto.PrincipalId.getDefaultInstance() : id_;
  }

  public static final int CREATED_AT_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return createdAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }

  public static final int PER_TENANT_ACLS_FIELD_NUMBER = 3;
  private static final class PerTenantAclsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs>newDefaultInstance(
                io.littlehorse.sdk.common.proto.Acls.internal_static_littlehorse_Principal_PerTenantAclsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                io.littlehorse.sdk.common.proto.ServerACLs.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs> perTenantAcls_;
  private com.google.protobuf.MapField<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs>
  internalGetPerTenantAcls() {
    if (perTenantAcls_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          PerTenantAclsDefaultEntryHolder.defaultEntry);
    }
    return perTenantAcls_;
  }
  public int getPerTenantAclsCount() {
    return internalGetPerTenantAcls().getMap().size();
  }
  /**
   * <pre>
   * Maps a Tenant ID to a list of ACL's that the Principal has permission to
   * execute *within that Tenant*
   * </pre>
   *
   * <code>map&lt;string, .littlehorse.ServerACLs&gt; per_tenant_acls = 3;</code>
   */
  @java.lang.Override
  public boolean containsPerTenantAcls(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetPerTenantAcls().getMap().containsKey(key);
  }
  /**
   * Use {@link #getPerTenantAclsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs> getPerTenantAcls() {
    return getPerTenantAclsMap();
  }
  /**
   * <pre>
   * Maps a Tenant ID to a list of ACL's that the Principal has permission to
   * execute *within that Tenant*
   * </pre>
   *
   * <code>map&lt;string, .littlehorse.ServerACLs&gt; per_tenant_acls = 3;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs> getPerTenantAclsMap() {
    return internalGetPerTenantAcls().getMap();
  }
  /**
   * <pre>
   * Maps a Tenant ID to a list of ACL's that the Principal has permission to
   * execute *within that Tenant*
   * </pre>
   *
   * <code>map&lt;string, .littlehorse.ServerACLs&gt; per_tenant_acls = 3;</code>
   */
  @java.lang.Override
  public /* nullable */
io.littlehorse.sdk.common.proto.ServerACLs getPerTenantAclsOrDefault(
      java.lang.String key,
      /* nullable */
io.littlehorse.sdk.common.proto.ServerACLs defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs> map =
        internalGetPerTenantAcls().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Maps a Tenant ID to a list of ACL's that the Principal has permission to
   * execute *within that Tenant*
   * </pre>
   *
   * <code>map&lt;string, .littlehorse.ServerACLs&gt; per_tenant_acls = 3;</code>
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.ServerACLs getPerTenantAclsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs> map =
        internalGetPerTenantAcls().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int GLOBAL_ACLS_FIELD_NUMBER = 4;
  private io.littlehorse.sdk.common.proto.ServerACLs globalAcls_;
  /**
   * <pre>
   * Sets permissions that this Principal has *for any Tenant* in the LH Cluster.
   * </pre>
   *
   * <code>.littlehorse.ServerACLs global_acls = 4;</code>
   * @return Whether the globalAcls field is set.
   */
  @java.lang.Override
  public boolean hasGlobalAcls() {
    return globalAcls_ != null;
  }
  /**
   * <pre>
   * Sets permissions that this Principal has *for any Tenant* in the LH Cluster.
   * </pre>
   *
   * <code>.littlehorse.ServerACLs global_acls = 4;</code>
   * @return The globalAcls.
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.ServerACLs getGlobalAcls() {
    return globalAcls_ == null ? io.littlehorse.sdk.common.proto.ServerACLs.getDefaultInstance() : globalAcls_;
  }
  /**
   * <pre>
   * Sets permissions that this Principal has *for any Tenant* in the LH Cluster.
   * </pre>
   *
   * <code>.littlehorse.ServerACLs global_acls = 4;</code>
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.ServerACLsOrBuilder getGlobalAclsOrBuilder() {
    return globalAcls_ == null ? io.littlehorse.sdk.common.proto.ServerACLs.getDefaultInstance() : globalAcls_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != null) {
      output.writeMessage(1, getId());
    }
    if (createdAt_ != null) {
      output.writeMessage(2, getCreatedAt());
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetPerTenantAcls(),
        PerTenantAclsDefaultEntryHolder.defaultEntry,
        3);
    if (globalAcls_ != null) {
      output.writeMessage(4, getGlobalAcls());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (createdAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCreatedAt());
    }
    for (java.util.Map.Entry<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs> entry
         : internalGetPerTenantAcls().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs>
      perTenantAcls__ = PerTenantAclsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, perTenantAcls__);
    }
    if (globalAcls_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getGlobalAcls());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.littlehorse.sdk.common.proto.Principal)) {
      return super.equals(obj);
    }
    io.littlehorse.sdk.common.proto.Principal other = (io.littlehorse.sdk.common.proto.Principal) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
    }
    if (!internalGetPerTenantAcls().equals(
        other.internalGetPerTenantAcls())) return false;
    if (hasGlobalAcls() != other.hasGlobalAcls()) return false;
    if (hasGlobalAcls()) {
      if (!getGlobalAcls()
          .equals(other.getGlobalAcls())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    if (!internalGetPerTenantAcls().getMap().isEmpty()) {
      hash = (37 * hash) + PER_TENANT_ACLS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetPerTenantAcls().hashCode();
    }
    if (hasGlobalAcls()) {
      hash = (37 * hash) + GLOBAL_ACLS_FIELD_NUMBER;
      hash = (53 * hash) + getGlobalAcls().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.littlehorse.sdk.common.proto.Principal parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.Principal parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.Principal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.Principal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.Principal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.Principal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.Principal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.sdk.common.proto.Principal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.littlehorse.sdk.common.proto.Principal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.littlehorse.sdk.common.proto.Principal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.Principal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.sdk.common.proto.Principal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.littlehorse.sdk.common.proto.Principal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * This is a GlobalGetable.
   * </pre>
   *
   * Protobuf type {@code littlehorse.Principal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:littlehorse.Principal)
      io.littlehorse.sdk.common.proto.PrincipalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.littlehorse.sdk.common.proto.Acls.internal_static_littlehorse_Principal_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetPerTenantAcls();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutablePerTenantAcls();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.littlehorse.sdk.common.proto.Acls.internal_static_littlehorse_Principal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.littlehorse.sdk.common.proto.Principal.class, io.littlehorse.sdk.common.proto.Principal.Builder.class);
    }

    // Construct using io.littlehorse.sdk.common.proto.Principal.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      internalGetMutablePerTenantAcls().clear();
      globalAcls_ = null;
      if (globalAclsBuilder_ != null) {
        globalAclsBuilder_.dispose();
        globalAclsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.littlehorse.sdk.common.proto.Acls.internal_static_littlehorse_Principal_descriptor;
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.Principal getDefaultInstanceForType() {
      return io.littlehorse.sdk.common.proto.Principal.getDefaultInstance();
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.Principal build() {
      io.littlehorse.sdk.common.proto.Principal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.Principal buildPartial() {
      io.littlehorse.sdk.common.proto.Principal result = new io.littlehorse.sdk.common.proto.Principal(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.littlehorse.sdk.common.proto.Principal result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = idBuilder_ == null
            ? id_
            : idBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.createdAt_ = createdAtBuilder_ == null
            ? createdAt_
            : createdAtBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.perTenantAcls_ = internalGetPerTenantAcls();
        result.perTenantAcls_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.globalAcls_ = globalAclsBuilder_ == null
            ? globalAcls_
            : globalAclsBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.littlehorse.sdk.common.proto.Principal) {
        return mergeFrom((io.littlehorse.sdk.common.proto.Principal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.littlehorse.sdk.common.proto.Principal other) {
      if (other == io.littlehorse.sdk.common.proto.Principal.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      internalGetMutablePerTenantAcls().mergeFrom(
          other.internalGetPerTenantAcls());
      bitField0_ |= 0x00000004;
      if (other.hasGlobalAcls()) {
        mergeGlobalAcls(other.getGlobalAcls());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getCreatedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.google.protobuf.MapEntry<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs>
              perTenantAcls__ = input.readMessage(
                  PerTenantAclsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutablePerTenantAcls().getMutableMap().put(
                  perTenantAcls__.getKey(), perTenantAcls__.getValue());
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getGlobalAclsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private io.littlehorse.sdk.common.proto.PrincipalId id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.sdk.common.proto.PrincipalId, io.littlehorse.sdk.common.proto.PrincipalId.Builder, io.littlehorse.sdk.common.proto.PrincipalIdOrBuilder> idBuilder_;
    /**
     * <pre>
     * Principals are agnostic of the Authentication protocol that you use. In OAuth,
     * the id is retrieved by looking at the claims on the request. In mTLS, the
     * id is retrived by looking at the Subject Name of the client certificate.
     * </pre>
     *
     * <code>.littlehorse.PrincipalId id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Principals are agnostic of the Authentication protocol that you use. In OAuth,
     * the id is retrieved by looking at the claims on the request. In mTLS, the
     * id is retrived by looking at the Subject Name of the client certificate.
     * </pre>
     *
     * <code>.littlehorse.PrincipalId id = 1;</code>
     * @return The id.
     */
    public io.littlehorse.sdk.common.proto.PrincipalId getId() {
      if (idBuilder_ == null) {
        return id_ == null ? io.littlehorse.sdk.common.proto.PrincipalId.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Principals are agnostic of the Authentication protocol that you use. In OAuth,
     * the id is retrieved by looking at the claims on the request. In mTLS, the
     * id is retrived by looking at the Subject Name of the client certificate.
     * </pre>
     *
     * <code>.littlehorse.PrincipalId id = 1;</code>
     */
    public Builder setId(io.littlehorse.sdk.common.proto.PrincipalId value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
      } else {
        idBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Principals are agnostic of the Authentication protocol that you use. In OAuth,
     * the id is retrieved by looking at the claims on the request. In mTLS, the
     * id is retrived by looking at the Subject Name of the client certificate.
     * </pre>
     *
     * <code>.littlehorse.PrincipalId id = 1;</code>
     */
    public Builder setId(
        io.littlehorse.sdk.common.proto.PrincipalId.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Principals are agnostic of the Authentication protocol that you use. In OAuth,
     * the id is retrieved by looking at the claims on the request. In mTLS, the
     * id is retrived by looking at the Subject Name of the client certificate.
     * </pre>
     *
     * <code>.littlehorse.PrincipalId id = 1;</code>
     */
    public Builder mergeId(io.littlehorse.sdk.common.proto.PrincipalId value) {
      if (idBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          id_ != null &&
          id_ != io.littlehorse.sdk.common.proto.PrincipalId.getDefaultInstance()) {
          getIdBuilder().mergeFrom(value);
        } else {
          id_ = value;
        }
      } else {
        idBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Principals are agnostic of the Authentication protocol that you use. In OAuth,
     * the id is retrieved by looking at the claims on the request. In mTLS, the
     * id is retrived by looking at the Subject Name of the client certificate.
     * </pre>
     *
     * <code>.littlehorse.PrincipalId id = 1;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Principals are agnostic of the Authentication protocol that you use. In OAuth,
     * the id is retrieved by looking at the claims on the request. In mTLS, the
     * id is retrived by looking at the Subject Name of the client certificate.
     * </pre>
     *
     * <code>.littlehorse.PrincipalId id = 1;</code>
     */
    public io.littlehorse.sdk.common.proto.PrincipalId.Builder getIdBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Principals are agnostic of the Authentication protocol that you use. In OAuth,
     * the id is retrieved by looking at the claims on the request. In mTLS, the
     * id is retrived by looking at the Subject Name of the client certificate.
     * </pre>
     *
     * <code>.littlehorse.PrincipalId id = 1;</code>
     */
    public io.littlehorse.sdk.common.proto.PrincipalIdOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            io.littlehorse.sdk.common.proto.PrincipalId.getDefaultInstance() : id_;
      }
    }
    /**
     * <pre>
     * Principals are agnostic of the Authentication protocol that you use. In OAuth,
     * the id is retrieved by looking at the claims on the request. In mTLS, the
     * id is retrived by looking at the Subject Name of the client certificate.
     * </pre>
     *
     * <code>.littlehorse.PrincipalId id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.sdk.common.proto.PrincipalId, io.littlehorse.sdk.common.proto.PrincipalId.Builder, io.littlehorse.sdk.common.proto.PrincipalIdOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.littlehorse.sdk.common.proto.PrincipalId, io.littlehorse.sdk.common.proto.PrincipalId.Builder, io.littlehorse.sdk.common.proto.PrincipalIdOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
      } else {
        createdAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          createdAt_ != null &&
          createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreatedAtBuilder().mergeFrom(value);
        } else {
          createdAt_ = value;
        }
      } else {
        createdAtBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000002);
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs> perTenantAcls_;
    private com.google.protobuf.MapField<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs>
        internalGetPerTenantAcls() {
      if (perTenantAcls_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PerTenantAclsDefaultEntryHolder.defaultEntry);
      }
      return perTenantAcls_;
    }
    private com.google.protobuf.MapField<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs>
        internalGetMutablePerTenantAcls() {
      if (perTenantAcls_ == null) {
        perTenantAcls_ = com.google.protobuf.MapField.newMapField(
            PerTenantAclsDefaultEntryHolder.defaultEntry);
      }
      if (!perTenantAcls_.isMutable()) {
        perTenantAcls_ = perTenantAcls_.copy();
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return perTenantAcls_;
    }
    public int getPerTenantAclsCount() {
      return internalGetPerTenantAcls().getMap().size();
    }
    /**
     * <pre>
     * Maps a Tenant ID to a list of ACL's that the Principal has permission to
     * execute *within that Tenant*
     * </pre>
     *
     * <code>map&lt;string, .littlehorse.ServerACLs&gt; per_tenant_acls = 3;</code>
     */
    @java.lang.Override
    public boolean containsPerTenantAcls(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetPerTenantAcls().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPerTenantAclsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs> getPerTenantAcls() {
      return getPerTenantAclsMap();
    }
    /**
     * <pre>
     * Maps a Tenant ID to a list of ACL's that the Principal has permission to
     * execute *within that Tenant*
     * </pre>
     *
     * <code>map&lt;string, .littlehorse.ServerACLs&gt; per_tenant_acls = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs> getPerTenantAclsMap() {
      return internalGetPerTenantAcls().getMap();
    }
    /**
     * <pre>
     * Maps a Tenant ID to a list of ACL's that the Principal has permission to
     * execute *within that Tenant*
     * </pre>
     *
     * <code>map&lt;string, .littlehorse.ServerACLs&gt; per_tenant_acls = 3;</code>
     */
    @java.lang.Override
    public /* nullable */
io.littlehorse.sdk.common.proto.ServerACLs getPerTenantAclsOrDefault(
        java.lang.String key,
        /* nullable */
io.littlehorse.sdk.common.proto.ServerACLs defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs> map =
          internalGetPerTenantAcls().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Maps a Tenant ID to a list of ACL's that the Principal has permission to
     * execute *within that Tenant*
     * </pre>
     *
     * <code>map&lt;string, .littlehorse.ServerACLs&gt; per_tenant_acls = 3;</code>
     */
    @java.lang.Override
    public io.littlehorse.sdk.common.proto.ServerACLs getPerTenantAclsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs> map =
          internalGetPerTenantAcls().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearPerTenantAcls() {
      bitField0_ = (bitField0_ & ~0x00000004);
      internalGetMutablePerTenantAcls().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * Maps a Tenant ID to a list of ACL's that the Principal has permission to
     * execute *within that Tenant*
     * </pre>
     *
     * <code>map&lt;string, .littlehorse.ServerACLs&gt; per_tenant_acls = 3;</code>
     */
    public Builder removePerTenantAcls(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutablePerTenantAcls().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs>
        getMutablePerTenantAcls() {
      bitField0_ |= 0x00000004;
      return internalGetMutablePerTenantAcls().getMutableMap();
    }
    /**
     * <pre>
     * Maps a Tenant ID to a list of ACL's that the Principal has permission to
     * execute *within that Tenant*
     * </pre>
     *
     * <code>map&lt;string, .littlehorse.ServerACLs&gt; per_tenant_acls = 3;</code>
     */
    public Builder putPerTenantAcls(
        java.lang.String key,
        io.littlehorse.sdk.common.proto.ServerACLs value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutablePerTenantAcls().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * Maps a Tenant ID to a list of ACL's that the Principal has permission to
     * execute *within that Tenant*
     * </pre>
     *
     * <code>map&lt;string, .littlehorse.ServerACLs&gt; per_tenant_acls = 3;</code>
     */
    public Builder putAllPerTenantAcls(
        java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ServerACLs> values) {
      internalGetMutablePerTenantAcls().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000004;
      return this;
    }

    private io.littlehorse.sdk.common.proto.ServerACLs globalAcls_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.sdk.common.proto.ServerACLs, io.littlehorse.sdk.common.proto.ServerACLs.Builder, io.littlehorse.sdk.common.proto.ServerACLsOrBuilder> globalAclsBuilder_;
    /**
     * <pre>
     * Sets permissions that this Principal has *for any Tenant* in the LH Cluster.
     * </pre>
     *
     * <code>.littlehorse.ServerACLs global_acls = 4;</code>
     * @return Whether the globalAcls field is set.
     */
    public boolean hasGlobalAcls() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Sets permissions that this Principal has *for any Tenant* in the LH Cluster.
     * </pre>
     *
     * <code>.littlehorse.ServerACLs global_acls = 4;</code>
     * @return The globalAcls.
     */
    public io.littlehorse.sdk.common.proto.ServerACLs getGlobalAcls() {
      if (globalAclsBuilder_ == null) {
        return globalAcls_ == null ? io.littlehorse.sdk.common.proto.ServerACLs.getDefaultInstance() : globalAcls_;
      } else {
        return globalAclsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Sets permissions that this Principal has *for any Tenant* in the LH Cluster.
     * </pre>
     *
     * <code>.littlehorse.ServerACLs global_acls = 4;</code>
     */
    public Builder setGlobalAcls(io.littlehorse.sdk.common.proto.ServerACLs value) {
      if (globalAclsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        globalAcls_ = value;
      } else {
        globalAclsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Sets permissions that this Principal has *for any Tenant* in the LH Cluster.
     * </pre>
     *
     * <code>.littlehorse.ServerACLs global_acls = 4;</code>
     */
    public Builder setGlobalAcls(
        io.littlehorse.sdk.common.proto.ServerACLs.Builder builderForValue) {
      if (globalAclsBuilder_ == null) {
        globalAcls_ = builderForValue.build();
      } else {
        globalAclsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Sets permissions that this Principal has *for any Tenant* in the LH Cluster.
     * </pre>
     *
     * <code>.littlehorse.ServerACLs global_acls = 4;</code>
     */
    public Builder mergeGlobalAcls(io.littlehorse.sdk.common.proto.ServerACLs value) {
      if (globalAclsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          globalAcls_ != null &&
          globalAcls_ != io.littlehorse.sdk.common.proto.ServerACLs.getDefaultInstance()) {
          getGlobalAclsBuilder().mergeFrom(value);
        } else {
          globalAcls_ = value;
        }
      } else {
        globalAclsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Sets permissions that this Principal has *for any Tenant* in the LH Cluster.
     * </pre>
     *
     * <code>.littlehorse.ServerACLs global_acls = 4;</code>
     */
    public Builder clearGlobalAcls() {
      bitField0_ = (bitField0_ & ~0x00000008);
      globalAcls_ = null;
      if (globalAclsBuilder_ != null) {
        globalAclsBuilder_.dispose();
        globalAclsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Sets permissions that this Principal has *for any Tenant* in the LH Cluster.
     * </pre>
     *
     * <code>.littlehorse.ServerACLs global_acls = 4;</code>
     */
    public io.littlehorse.sdk.common.proto.ServerACLs.Builder getGlobalAclsBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getGlobalAclsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Sets permissions that this Principal has *for any Tenant* in the LH Cluster.
     * </pre>
     *
     * <code>.littlehorse.ServerACLs global_acls = 4;</code>
     */
    public io.littlehorse.sdk.common.proto.ServerACLsOrBuilder getGlobalAclsOrBuilder() {
      if (globalAclsBuilder_ != null) {
        return globalAclsBuilder_.getMessageOrBuilder();
      } else {
        return globalAcls_ == null ?
            io.littlehorse.sdk.common.proto.ServerACLs.getDefaultInstance() : globalAcls_;
      }
    }
    /**
     * <pre>
     * Sets permissions that this Principal has *for any Tenant* in the LH Cluster.
     * </pre>
     *
     * <code>.littlehorse.ServerACLs global_acls = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.littlehorse.sdk.common.proto.ServerACLs, io.littlehorse.sdk.common.proto.ServerACLs.Builder, io.littlehorse.sdk.common.proto.ServerACLsOrBuilder> 
        getGlobalAclsFieldBuilder() {
      if (globalAclsBuilder_ == null) {
        globalAclsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.littlehorse.sdk.common.proto.ServerACLs, io.littlehorse.sdk.common.proto.ServerACLs.Builder, io.littlehorse.sdk.common.proto.ServerACLsOrBuilder>(
                getGlobalAcls(),
                getParentForChildren(),
                isClean());
        globalAcls_ = null;
      }
      return globalAclsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:littlehorse.Principal)
  }

  // @@protoc_insertion_point(class_scope:littlehorse.Principal)
  private static final io.littlehorse.sdk.common.proto.Principal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.littlehorse.sdk.common.proto.Principal();
  }

  public static io.littlehorse.sdk.common.proto.Principal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Principal>
      PARSER = new com.google.protobuf.AbstractParser<Principal>() {
    @java.lang.Override
    public Principal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Principal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Principal> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.littlehorse.sdk.common.proto.Principal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

