// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package io.littlehorse.sdk.common.proto;

public interface SearchExternalEventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.SearchExternalEventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Bookmark for cursor-based pagination; pass if applicable.
   * </pre>
   *
   * <code>optional bytes bookmark = 1;</code>
   * @return Whether the bookmark field is set.
   */
  boolean hasBookmark();
  /**
   * <pre>
   * Bookmark for cursor-based pagination; pass if applicable.
   * </pre>
   *
   * <code>optional bytes bookmark = 1;</code>
   * @return The bookmark.
   */
  com.google.protobuf.ByteString getBookmark();

  /**
   * <pre>
   * Maximum results to return in one request.
   * </pre>
   *
   * <code>optional int32 limit = 2;</code>
   * @return Whether the limit field is set.
   */
  boolean hasLimit();
  /**
   * <pre>
   * Maximum results to return in one request.
   * </pre>
   *
   * <code>optional int32 limit = 2;</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <code>.littlehorse.WfRunId wf_run_id = 3;</code>
   * @return Whether the wfRunId field is set.
   */
  boolean hasWfRunId();
  /**
   * <code>.littlehorse.WfRunId wf_run_id = 3;</code>
   * @return The wfRunId.
   */
  io.littlehorse.sdk.common.proto.WfRunId getWfRunId();
  /**
   * <code>.littlehorse.WfRunId wf_run_id = 3;</code>
   */
  io.littlehorse.sdk.common.proto.WfRunIdOrBuilder getWfRunIdOrBuilder();

  /**
   * <code>.littlehorse.SearchExternalEventRequest.ByExtEvtDefNameAndStatusRequest external_event_def_name_and_status = 4;</code>
   * @return Whether the externalEventDefNameAndStatus field is set.
   */
  boolean hasExternalEventDefNameAndStatus();
  /**
   * <code>.littlehorse.SearchExternalEventRequest.ByExtEvtDefNameAndStatusRequest external_event_def_name_and_status = 4;</code>
   * @return The externalEventDefNameAndStatus.
   */
  io.littlehorse.sdk.common.proto.SearchExternalEventRequest.ByExtEvtDefNameAndStatusRequest getExternalEventDefNameAndStatus();
  /**
   * <code>.littlehorse.SearchExternalEventRequest.ByExtEvtDefNameAndStatusRequest external_event_def_name_and_status = 4;</code>
   */
  io.littlehorse.sdk.common.proto.SearchExternalEventRequest.ByExtEvtDefNameAndStatusRequestOrBuilder getExternalEventDefNameAndStatusOrBuilder();

  io.littlehorse.sdk.common.proto.SearchExternalEventRequest.ExtEvtCriteriaCase getExtEvtCriteriaCase();
}
