// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: object_id.proto
// Protobuf Java Version: 4.29.3

package io.littlehorse.sdk.common.proto;

public interface UserTaskRunIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.UserTaskRunId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * WfRunId for this UserTaskRun. Note that every UserTaskRun is associated
   * with a WfRun.
   * </pre>
   *
   * <code>.littlehorse.WfRunId wf_run_id = 1;</code>
   * @return Whether the wfRunId field is set.
   */
  boolean hasWfRunId();
  /**
   * <pre>
   * WfRunId for this UserTaskRun. Note that every UserTaskRun is associated
   * with a WfRun.
   * </pre>
   *
   * <code>.littlehorse.WfRunId wf_run_id = 1;</code>
   * @return The wfRunId.
   */
  io.littlehorse.sdk.common.proto.WfRunId getWfRunId();
  /**
   * <pre>
   * WfRunId for this UserTaskRun. Note that every UserTaskRun is associated
   * with a WfRun.
   * </pre>
   *
   * <code>.littlehorse.WfRunId wf_run_id = 1;</code>
   */
  io.littlehorse.sdk.common.proto.WfRunIdOrBuilder getWfRunIdOrBuilder();

  /**
   * <pre>
   * Unique identifier for this UserTaskRun.
   * </pre>
   *
   * <code>string user_task_guid = 2;</code>
   * @return The userTaskGuid.
   */
  java.lang.String getUserTaskGuid();
  /**
   * <pre>
   * Unique identifier for this UserTaskRun.
   * </pre>
   *
   * <code>string user_task_guid = 2;</code>
   * @return The bytes for userTaskGuid.
   */
  com.google.protobuf.ByteString
      getUserTaskGuidBytes();
}
