// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_tasks.proto

package io.littlehorse.sdk.common.proto;

public final class UserTasks {
  private UserTasks() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskDef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskDef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskField_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskRun_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskRun_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskRun_ResultsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskRun_ResultsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_AssignUserTaskRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_AssignUserTaskRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_CompleteUserTaskRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_CompleteUserTaskRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_CompleteUserTaskRunRequest_ResultsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_CompleteUserTaskRunRequest_ResultsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_SaveUserTaskRunProgressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_SaveUserTaskRunProgressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_SaveUserTaskRunProgressRequest_ResultsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_SaveUserTaskRunProgressRequest_ResultsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_CancelUserTaskRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_CancelUserTaskRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskRunCommentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskRunCommentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_EditUserTaskRunCommentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_EditUserTaskRunCommentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_DeleteUserTaskRunCommentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_DeleteUserTaskRunCommentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskTriggerReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskTriggerReference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskEvent_UTECancelled_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskEvent_UTECancelled_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskEvent_UTETaskExecuted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskEvent_UTETaskExecuted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskEvent_UTESaved_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskEvent_UTESaved_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskEvent_UTESaved_ResultsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskEvent_UTESaved_ResultsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskEvent_UTEAssigned_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskEvent_UTEAssigned_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskEvent_UTECommented_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskEvent_UTECommented_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_UserTaskEvent_UTECommentDeleted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_littlehorse_UserTaskEvent_UTECommentDeleted_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020user_tasks.proto\022\013littlehorse\032\037google/" +
      "protobuf/timestamp.proto\032\022common_enums.p" +
      "roto\032\017object_id.proto\032\016variable.proto\"\262\001" +
      "\n\013UserTaskDef\022\014\n\004name\030\001 \001(\t\022\017\n\007version\030\002" +
      " \001(\005\022\030\n\013description\030\003 \001(\tH\000\210\001\001\022*\n\006fields" +
      "\030\004 \003(\0132\032.littlehorse.UserTaskField\022.\n\ncr" +
      "eated_at\030\005 \001(\0132\032.google.protobuf.Timesta" +
      "mpB\016\n\014_description\"\230\001\n\rUserTaskField\022\014\n\004" +
      "name\030\001 \001(\t\022\'\n\004type\030\002 \001(\0162\031.littlehorse.V" +
      "ariableType\022\030\n\013description\030\003 \001(\tH\000\210\001\001\022\024\n" +
      "\014display_name\030\004 \001(\t\022\020\n\010required\030\005 \001(\010B\016\n" +
      "\014_description\"\275\004\n\013UserTaskRun\022&\n\002id\030\001 \001(" +
      "\0132\032.littlehorse.UserTaskRunId\0224\n\020user_ta" +
      "sk_def_id\030\002 \001(\0132\032.littlehorse.UserTaskDe" +
      "fId\022\027\n\nuser_group\030\003 \001(\tH\000\210\001\001\022\024\n\007user_id\030" +
      "\004 \001(\tH\001\210\001\001\0226\n\007results\030\006 \003(\0132%.littlehors" +
      "e.UserTaskRun.ResultsEntry\022.\n\006status\030\007 \001" +
      "(\0162\036.littlehorse.UserTaskRunStatus\022*\n\006ev" +
      "ents\030\010 \003(\0132\032.littlehorse.UserTaskEvent\022\022" +
      "\n\005notes\030\t \001(\tH\002\210\001\001\0222\n\016scheduled_time\030\n \001" +
      "(\0132\032.google.protobuf.Timestamp\022+\n\013node_r" +
      "un_id\030\013 \001(\0132\026.littlehorse.NodeRunId\022\r\n\005e" +
      "poch\030\014 \001(\005\022\030\n\020comment_id_count\030\r \001(\005\032J\n\014" +
      "ResultsEntry\022\013\n\003key\030\001 \001(\t\022)\n\005value\030\002 \001(\013" +
      "2\032.littlehorse.VariableValue:\0028\001B\r\n\013_use" +
      "r_groupB\n\n\010_user_idB\010\n\006_notes\"\262\001\n\030Assign" +
      "UserTaskRunRequest\0224\n\020user_task_run_id\030\001" +
      " \001(\0132\032.littlehorse.UserTaskRunId\022\026\n\016over" +
      "ride_claim\030\002 \001(\010\022\027\n\nuser_group\030\003 \001(\tH\000\210\001" +
      "\001\022\024\n\007user_id\030\004 \001(\tH\001\210\001\001B\r\n\013_user_groupB\n" +
      "\n\010_user_id\"\366\001\n\032CompleteUserTaskRunReques" +
      "t\0224\n\020user_task_run_id\030\001 \001(\0132\032.littlehors" +
      "e.UserTaskRunId\022E\n\007results\030\002 \003(\01324.littl" +
      "ehorse.CompleteUserTaskRunRequest.Result" +
      "sEntry\022\017\n\007user_id\030\003 \001(\t\032J\n\014ResultsEntry\022" +
      "\013\n\003key\030\001 \001(\t\022)\n\005value\030\002 \001(\0132\032.littlehors" +
      "e.VariableValue:\0028\001\"\256\003\n\036SaveUserTaskRunP" +
      "rogressRequest\0224\n\020user_task_run_id\030\001 \001(\013" +
      "2\032.littlehorse.UserTaskRunId\022I\n\007results\030" +
      "\002 \003(\01328.littlehorse.SaveUserTaskRunProgr" +
      "essRequest.ResultsEntry\022\017\n\007user_id\030\003 \001(\t" +
      "\022[\n\006policy\030\004 \001(\0162K.littlehorse.SaveUserT" +
      "askRunProgressRequest.SaveUserTaskRunAss" +
      "ignmentPolicy\032J\n\014ResultsEntry\022\013\n\003key\030\001 \001" +
      "(\t\022)\n\005value\030\002 \001(\0132\032.littlehorse.Variable" +
      "Value:\0028\001\"Q\n\037SaveUserTaskRunAssignmentPo" +
      "licy\022\034\n\030FAIL_IF_CLAIMED_BY_OTHER\020\000\022\020\n\014IG" +
      "NORE_CLAIM\020\001\"P\n\030CancelUserTaskRunRequest" +
      "\0224\n\020user_task_run_id\030\001 \001(\0132\032.littlehorse" +
      ".UserTaskRunId\"s\n\031UserTaskRunCommentRequ" +
      "est\0224\n\020user_task_run_id\030\001 \001(\0132\032.littleho" +
      "rse.UserTaskRunId\022\017\n\007user_id\030\002 \001(\t\022\017\n\007co" +
      "mment\030\003 \001(\t\"\220\001\n\035EditUserTaskRunCommentRe" +
      "quest\022\027\n\017user_comment_id\030\001 \001(\005\0224\n\020user_t" +
      "ask_run_id\030\002 \001(\0132\032.littlehorse.UserTaskR" +
      "unId\022\017\n\007user_id\030\003 \001(\t\022\017\n\007comment\030\004 \001(\t\"p" +
      "\n\037DeleteUserTaskRunCommentRequest\0224\n\020use" +
      "r_task_run_id\030\001 \001(\0132\032.littlehorse.UserTa" +
      "skRunId\022\027\n\017user_comment_id\030\002 \001(\005\"\261\001\n\030Use" +
      "rTaskTriggerReference\022+\n\013node_run_id\030\001 \001" +
      "(\0132\026.littlehorse.NodeRunId\022\036\n\026user_task_" +
      "event_number\030\002 \001(\005\022\024\n\007user_id\030\003 \001(\tH\000\210\001\001" +
      "\022\027\n\nuser_group\030\004 \001(\tH\001\210\001\001B\n\n\010_user_idB\r\n" +
      "\013_user_group\"\315\010\n\rUserTaskEvent\022(\n\004time\030\001" +
      " \001(\0132\032.google.protobuf.Timestamp\022C\n\rtask" +
      "_executed\030\002 \001(\0132*.littlehorse.UserTaskEv" +
      "ent.UTETaskExecutedH\000\022:\n\010assigned\030\003 \001(\0132" +
      "&.littlehorse.UserTaskEvent.UTEAssignedH" +
      "\000\022<\n\tcancelled\030\004 \001(\0132\'.littlehorse.UserT" +
      "askEvent.UTECancelledH\000\0224\n\005saved\030\005 \001(\0132#" +
      ".littlehorse.UserTaskEvent.UTESavedH\000\022@\n" +
      "\rcomment_added\030\006 \001(\0132\'.littlehorse.UserT" +
      "askEvent.UTECommentedH\000\022A\n\016comment_edite" +
      "d\030\007 \001(\0132\'.littlehorse.UserTaskEvent.UTEC" +
      "ommentedH\000\022G\n\017comment_deleted\030\010 \001(\0132,.li" +
      "ttlehorse.UserTaskEvent.UTECommentDelete" +
      "dH\000\032\037\n\014UTECancelled\022\017\n\007message\030\001 \001(\t\032;\n\017" +
      "UTETaskExecuted\022(\n\010task_run\030\001 \001(\0132\026.litt" +
      "lehorse.TaskRunId\032\252\001\n\010UTESaved\022\017\n\007user_i" +
      "d\030\001 \001(\t\022A\n\007results\030\002 \003(\01320.littlehorse.U" +
      "serTaskEvent.UTESaved.ResultsEntry\032J\n\014Re" +
      "sultsEntry\022\013\n\003key\030\001 \001(\t\022)\n\005value\030\002 \001(\0132\032" +
      ".littlehorse.VariableValue:\0028\001\032\301\001\n\013UTEAs" +
      "signed\022\030\n\013old_user_id\030\001 \001(\tH\000\210\001\001\022\033\n\016old_" +
      "user_group\030\002 \001(\tH\001\210\001\001\022\030\n\013new_user_id\030\003 \001" +
      "(\tH\002\210\001\001\022\033\n\016new_user_group\030\004 \001(\tH\003\210\001\001B\016\n\014" +
      "_old_user_idB\021\n\017_old_user_groupB\016\n\014_new_" +
      "user_idB\021\n\017_new_user_group\032I\n\014UTEComment" +
      "ed\022\027\n\017user_comment_id\030\001 \001(\005\022\017\n\007user_id\030\002" +
      " \001(\t\022\017\n\007comment\030\003 \001(\t\032,\n\021UTECommentDelet" +
      "ed\022\027\n\017user_comment_id\030\001 \001(\005B\007\n\005event*J\n\021" +
      "UserTaskRunStatus\022\016\n\nUNASSIGNED\020\000\022\014\n\010ASS" +
      "IGNED\020\001\022\010\n\004DONE\020\003\022\r\n\tCANCELLED\020\004BM\n\037io.l" +
      "ittlehorse.sdk.common.protoP\001Z\t.;lhproto" +
      "\252\002\034LittleHorse.Sdk.Common.Protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          io.littlehorse.sdk.common.proto.CommonEnums.getDescriptor(),
          io.littlehorse.sdk.common.proto.ObjectId.getDescriptor(),
          io.littlehorse.sdk.common.proto.VariableOuterClass.getDescriptor(),
        });
    internal_static_littlehorse_UserTaskDef_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_littlehorse_UserTaskDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskDef_descriptor,
        new java.lang.String[] { "Name", "Version", "Description", "Fields", "CreatedAt", "Description", });
    internal_static_littlehorse_UserTaskField_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_littlehorse_UserTaskField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskField_descriptor,
        new java.lang.String[] { "Name", "Type", "Description", "DisplayName", "Required", "Description", });
    internal_static_littlehorse_UserTaskRun_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_littlehorse_UserTaskRun_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskRun_descriptor,
        new java.lang.String[] { "Id", "UserTaskDefId", "UserGroup", "UserId", "Results", "Status", "Events", "Notes", "ScheduledTime", "NodeRunId", "Epoch", "CommentIdCount", "UserGroup", "UserId", "Notes", });
    internal_static_littlehorse_UserTaskRun_ResultsEntry_descriptor =
      internal_static_littlehorse_UserTaskRun_descriptor.getNestedTypes().get(0);
    internal_static_littlehorse_UserTaskRun_ResultsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskRun_ResultsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_littlehorse_AssignUserTaskRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_littlehorse_AssignUserTaskRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_AssignUserTaskRunRequest_descriptor,
        new java.lang.String[] { "UserTaskRunId", "OverrideClaim", "UserGroup", "UserId", "UserGroup", "UserId", });
    internal_static_littlehorse_CompleteUserTaskRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_littlehorse_CompleteUserTaskRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_CompleteUserTaskRunRequest_descriptor,
        new java.lang.String[] { "UserTaskRunId", "Results", "UserId", });
    internal_static_littlehorse_CompleteUserTaskRunRequest_ResultsEntry_descriptor =
      internal_static_littlehorse_CompleteUserTaskRunRequest_descriptor.getNestedTypes().get(0);
    internal_static_littlehorse_CompleteUserTaskRunRequest_ResultsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_CompleteUserTaskRunRequest_ResultsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_littlehorse_SaveUserTaskRunProgressRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_littlehorse_SaveUserTaskRunProgressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_SaveUserTaskRunProgressRequest_descriptor,
        new java.lang.String[] { "UserTaskRunId", "Results", "UserId", "Policy", });
    internal_static_littlehorse_SaveUserTaskRunProgressRequest_ResultsEntry_descriptor =
      internal_static_littlehorse_SaveUserTaskRunProgressRequest_descriptor.getNestedTypes().get(0);
    internal_static_littlehorse_SaveUserTaskRunProgressRequest_ResultsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_SaveUserTaskRunProgressRequest_ResultsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_littlehorse_CancelUserTaskRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_littlehorse_CancelUserTaskRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_CancelUserTaskRunRequest_descriptor,
        new java.lang.String[] { "UserTaskRunId", });
    internal_static_littlehorse_UserTaskRunCommentRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_littlehorse_UserTaskRunCommentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskRunCommentRequest_descriptor,
        new java.lang.String[] { "UserTaskRunId", "UserId", "Comment", });
    internal_static_littlehorse_EditUserTaskRunCommentRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_littlehorse_EditUserTaskRunCommentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_EditUserTaskRunCommentRequest_descriptor,
        new java.lang.String[] { "UserCommentId", "UserTaskRunId", "UserId", "Comment", });
    internal_static_littlehorse_DeleteUserTaskRunCommentRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_littlehorse_DeleteUserTaskRunCommentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_DeleteUserTaskRunCommentRequest_descriptor,
        new java.lang.String[] { "UserTaskRunId", "UserCommentId", });
    internal_static_littlehorse_UserTaskTriggerReference_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_littlehorse_UserTaskTriggerReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskTriggerReference_descriptor,
        new java.lang.String[] { "NodeRunId", "UserTaskEventNumber", "UserId", "UserGroup", "UserId", "UserGroup", });
    internal_static_littlehorse_UserTaskEvent_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_littlehorse_UserTaskEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskEvent_descriptor,
        new java.lang.String[] { "Time", "TaskExecuted", "Assigned", "Cancelled", "Saved", "CommentAdded", "CommentEdited", "CommentDeleted", "Event", });
    internal_static_littlehorse_UserTaskEvent_UTECancelled_descriptor =
      internal_static_littlehorse_UserTaskEvent_descriptor.getNestedTypes().get(0);
    internal_static_littlehorse_UserTaskEvent_UTECancelled_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskEvent_UTECancelled_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_littlehorse_UserTaskEvent_UTETaskExecuted_descriptor =
      internal_static_littlehorse_UserTaskEvent_descriptor.getNestedTypes().get(1);
    internal_static_littlehorse_UserTaskEvent_UTETaskExecuted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskEvent_UTETaskExecuted_descriptor,
        new java.lang.String[] { "TaskRun", });
    internal_static_littlehorse_UserTaskEvent_UTESaved_descriptor =
      internal_static_littlehorse_UserTaskEvent_descriptor.getNestedTypes().get(2);
    internal_static_littlehorse_UserTaskEvent_UTESaved_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskEvent_UTESaved_descriptor,
        new java.lang.String[] { "UserId", "Results", });
    internal_static_littlehorse_UserTaskEvent_UTESaved_ResultsEntry_descriptor =
      internal_static_littlehorse_UserTaskEvent_UTESaved_descriptor.getNestedTypes().get(0);
    internal_static_littlehorse_UserTaskEvent_UTESaved_ResultsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskEvent_UTESaved_ResultsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_littlehorse_UserTaskEvent_UTEAssigned_descriptor =
      internal_static_littlehorse_UserTaskEvent_descriptor.getNestedTypes().get(3);
    internal_static_littlehorse_UserTaskEvent_UTEAssigned_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskEvent_UTEAssigned_descriptor,
        new java.lang.String[] { "OldUserId", "OldUserGroup", "NewUserId", "NewUserGroup", "OldUserId", "OldUserGroup", "NewUserId", "NewUserGroup", });
    internal_static_littlehorse_UserTaskEvent_UTECommented_descriptor =
      internal_static_littlehorse_UserTaskEvent_descriptor.getNestedTypes().get(4);
    internal_static_littlehorse_UserTaskEvent_UTECommented_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskEvent_UTECommented_descriptor,
        new java.lang.String[] { "UserCommentId", "UserId", "Comment", });
    internal_static_littlehorse_UserTaskEvent_UTECommentDeleted_descriptor =
      internal_static_littlehorse_UserTaskEvent_descriptor.getNestedTypes().get(5);
    internal_static_littlehorse_UserTaskEvent_UTECommentDeleted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_littlehorse_UserTaskEvent_UTECommentDeleted_descriptor,
        new java.lang.String[] { "UserCommentId", });
    com.google.protobuf.TimestampProto.getDescriptor();
    io.littlehorse.sdk.common.proto.CommonEnums.getDescriptor();
    io.littlehorse.sdk.common.proto.ObjectId.getDescriptor();
    io.littlehorse.sdk.common.proto.VariableOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
