// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package io.littlehorse.sdk.common.proto;

public interface WaitForThreadsRunPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.WaitForThreadsRunPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .littlehorse.WaitForThreadsRunPb.WaitForThreadPb threads = 1;</code>
   */
  java.util.List<io.littlehorse.sdk.common.proto.WaitForThreadsRunPb.WaitForThreadPb> 
      getThreadsList();
  /**
   * <code>repeated .littlehorse.WaitForThreadsRunPb.WaitForThreadPb threads = 1;</code>
   */
  io.littlehorse.sdk.common.proto.WaitForThreadsRunPb.WaitForThreadPb getThreads(int index);
  /**
   * <code>repeated .littlehorse.WaitForThreadsRunPb.WaitForThreadPb threads = 1;</code>
   */
  int getThreadsCount();
  /**
   * <code>repeated .littlehorse.WaitForThreadsRunPb.WaitForThreadPb threads = 1;</code>
   */
  java.util.List<? extends io.littlehorse.sdk.common.proto.WaitForThreadsRunPb.WaitForThreadPbOrBuilder> 
      getThreadsOrBuilderList();
  /**
   * <code>repeated .littlehorse.WaitForThreadsRunPb.WaitForThreadPb threads = 1;</code>
   */
  io.littlehorse.sdk.common.proto.WaitForThreadsRunPb.WaitForThreadPbOrBuilder getThreadsOrBuilder(
      int index);
}
