// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: wf_run_migration.proto
// Protobuf Java Version: 4.32.1

package io.littlehorse.sdk.common.proto;

@com.google.protobuf.Generated
public interface WfRunMigrationPlanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.WfRunMigrationPlan)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name and id
   * </pre>
   *
   * <code>.littlehorse.MigrationPlanId id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   * Name and id
   * </pre>
   *
   * <code>.littlehorse.MigrationPlanId id = 1;</code>
   * @return The id.
   */
  io.littlehorse.sdk.common.proto.MigrationPlanId getId();
  /**
   * <pre>
   * Name and id
   * </pre>
   *
   * <code>.littlehorse.MigrationPlanId id = 1;</code>
   */
  io.littlehorse.sdk.common.proto.MigrationPlanIdOrBuilder getIdOrBuilder();

  /**
   * <pre>
   * When the MigrationPlan was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <pre>
   * When the MigrationPlan was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <pre>
   * When the MigrationPlan was created.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <pre>
   * Name of old thread -&gt; How to migrate thread
   * </pre>
   *
   * <code>.littlehorse.MigrationPlan migration_plan = 3;</code>
   * @return Whether the migrationPlan field is set.
   */
  boolean hasMigrationPlan();
  /**
   * <pre>
   * Name of old thread -&gt; How to migrate thread
   * </pre>
   *
   * <code>.littlehorse.MigrationPlan migration_plan = 3;</code>
   * @return The migrationPlan.
   */
  io.littlehorse.sdk.common.proto.MigrationPlan getMigrationPlan();
  /**
   * <pre>
   * Name of old thread -&gt; How to migrate thread
   * </pre>
   *
   * <code>.littlehorse.MigrationPlan migration_plan = 3;</code>
   */
  io.littlehorse.sdk.common.proto.MigrationPlanOrBuilder getMigrationPlanOrBuilder();
}
