// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lh_proto.proto

package io.littlehorse.common.proto;

/**
 * Protobuf type {@code lh_proto.TaskCompleteOePb}
 */
public final class TaskCompleteOePb extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lh_proto.TaskCompleteOePb)
    TaskCompleteOePbOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TaskCompleteOePb.newBuilder() to construct.
  private TaskCompleteOePb(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TaskCompleteOePb() {
    output_ = com.google.protobuf.ByteString.EMPTY;
    logOutput_ = com.google.protobuf.ByteString.EMPTY;
    nodeName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TaskCompleteOePb();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TaskCompleteOePb(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            threadRunNumber_ = input.readInt32();
            break;
          }
          case 16: {

            taskRunNumber_ = input.readInt32();
            break;
          }
          case 24: {

            taskRunPosition_ = input.readInt32();
            break;
          }
          case 32: {

            success_ = input.readBool();
            break;
          }
          case 42: {
            bitField0_ |= 0x00000001;
            output_ = input.readBytes();
            break;
          }
          case 50: {
            bitField0_ |= 0x00000002;
            logOutput_ = input.readBytes();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            nodeName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.littlehorse.common.proto.LhProto.internal_static_lh_proto_TaskCompleteOePb_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.littlehorse.common.proto.LhProto.internal_static_lh_proto_TaskCompleteOePb_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.littlehorse.common.proto.TaskCompleteOePb.class, io.littlehorse.common.proto.TaskCompleteOePb.Builder.class);
  }

  private int bitField0_;
  public static final int THREAD_RUN_NUMBER_FIELD_NUMBER = 1;
  private int threadRunNumber_;
  /**
   * <code>int32 thread_run_number = 1;</code>
   * @return The threadRunNumber.
   */
  @java.lang.Override
  public int getThreadRunNumber() {
    return threadRunNumber_;
  }

  public static final int TASK_RUN_NUMBER_FIELD_NUMBER = 2;
  private int taskRunNumber_;
  /**
   * <code>int32 task_run_number = 2;</code>
   * @return The taskRunNumber.
   */
  @java.lang.Override
  public int getTaskRunNumber() {
    return taskRunNumber_;
  }

  public static final int TASK_RUN_POSITION_FIELD_NUMBER = 3;
  private int taskRunPosition_;
  /**
   * <code>int32 task_run_position = 3;</code>
   * @return The taskRunPosition.
   */
  @java.lang.Override
  public int getTaskRunPosition() {
    return taskRunPosition_;
  }

  public static final int SUCCESS_FIELD_NUMBER = 4;
  private boolean success_;
  /**
   * <code>bool success = 4;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int OUTPUT_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString output_;
  /**
   * <code>bytes output = 5;</code>
   * @return Whether the output field is set.
   */
  @java.lang.Override
  public boolean hasOutput() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>bytes output = 5;</code>
   * @return The output.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getOutput() {
    return output_;
  }

  public static final int LOG_OUTPUT_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString logOutput_;
  /**
   * <code>bytes log_output = 6;</code>
   * @return Whether the logOutput field is set.
   */
  @java.lang.Override
  public boolean hasLogOutput() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>bytes log_output = 6;</code>
   * @return The logOutput.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getLogOutput() {
    return logOutput_;
  }

  public static final int NODE_NAME_FIELD_NUMBER = 7;
  private volatile java.lang.Object nodeName_;
  /**
   * <code>string node_name = 7;</code>
   * @return The nodeName.
   */
  @java.lang.Override
  public java.lang.String getNodeName() {
    java.lang.Object ref = nodeName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nodeName_ = s;
      return s;
    }
  }
  /**
   * <code>string node_name = 7;</code>
   * @return The bytes for nodeName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNodeNameBytes() {
    java.lang.Object ref = nodeName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nodeName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (threadRunNumber_ != 0) {
      output.writeInt32(1, threadRunNumber_);
    }
    if (taskRunNumber_ != 0) {
      output.writeInt32(2, taskRunNumber_);
    }
    if (taskRunPosition_ != 0) {
      output.writeInt32(3, taskRunPosition_);
    }
    if (success_ != false) {
      output.writeBool(4, success_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBytes(5, output_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBytes(6, logOutput_);
    }
    if (!getNodeNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, nodeName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (threadRunNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, threadRunNumber_);
    }
    if (taskRunNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, taskRunNumber_);
    }
    if (taskRunPosition_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, taskRunPosition_);
    }
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, success_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, output_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, logOutput_);
    }
    if (!getNodeNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, nodeName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.littlehorse.common.proto.TaskCompleteOePb)) {
      return super.equals(obj);
    }
    io.littlehorse.common.proto.TaskCompleteOePb other = (io.littlehorse.common.proto.TaskCompleteOePb) obj;

    if (getThreadRunNumber()
        != other.getThreadRunNumber()) return false;
    if (getTaskRunNumber()
        != other.getTaskRunNumber()) return false;
    if (getTaskRunPosition()
        != other.getTaskRunPosition()) return false;
    if (getSuccess()
        != other.getSuccess()) return false;
    if (hasOutput() != other.hasOutput()) return false;
    if (hasOutput()) {
      if (!getOutput()
          .equals(other.getOutput())) return false;
    }
    if (hasLogOutput() != other.hasLogOutput()) return false;
    if (hasLogOutput()) {
      if (!getLogOutput()
          .equals(other.getLogOutput())) return false;
    }
    if (!getNodeName()
        .equals(other.getNodeName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + THREAD_RUN_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getThreadRunNumber();
    hash = (37 * hash) + TASK_RUN_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getTaskRunNumber();
    hash = (37 * hash) + TASK_RUN_POSITION_FIELD_NUMBER;
    hash = (53 * hash) + getTaskRunPosition();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    if (hasOutput()) {
      hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
      hash = (53 * hash) + getOutput().hashCode();
    }
    if (hasLogOutput()) {
      hash = (37 * hash) + LOG_OUTPUT_FIELD_NUMBER;
      hash = (53 * hash) + getLogOutput().hashCode();
    }
    hash = (37 * hash) + NODE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getNodeName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.littlehorse.common.proto.TaskCompleteOePb parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.common.proto.TaskCompleteOePb parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.common.proto.TaskCompleteOePb parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.common.proto.TaskCompleteOePb parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.common.proto.TaskCompleteOePb parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.common.proto.TaskCompleteOePb parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.common.proto.TaskCompleteOePb parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.common.proto.TaskCompleteOePb parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.common.proto.TaskCompleteOePb parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.littlehorse.common.proto.TaskCompleteOePb parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.common.proto.TaskCompleteOePb parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.common.proto.TaskCompleteOePb parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.littlehorse.common.proto.TaskCompleteOePb prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lh_proto.TaskCompleteOePb}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lh_proto.TaskCompleteOePb)
      io.littlehorse.common.proto.TaskCompleteOePbOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.littlehorse.common.proto.LhProto.internal_static_lh_proto_TaskCompleteOePb_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.littlehorse.common.proto.LhProto.internal_static_lh_proto_TaskCompleteOePb_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.littlehorse.common.proto.TaskCompleteOePb.class, io.littlehorse.common.proto.TaskCompleteOePb.Builder.class);
    }

    // Construct using io.littlehorse.common.proto.TaskCompleteOePb.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      threadRunNumber_ = 0;

      taskRunNumber_ = 0;

      taskRunPosition_ = 0;

      success_ = false;

      output_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      logOutput_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      nodeName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.littlehorse.common.proto.LhProto.internal_static_lh_proto_TaskCompleteOePb_descriptor;
    }

    @java.lang.Override
    public io.littlehorse.common.proto.TaskCompleteOePb getDefaultInstanceForType() {
      return io.littlehorse.common.proto.TaskCompleteOePb.getDefaultInstance();
    }

    @java.lang.Override
    public io.littlehorse.common.proto.TaskCompleteOePb build() {
      io.littlehorse.common.proto.TaskCompleteOePb result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.littlehorse.common.proto.TaskCompleteOePb buildPartial() {
      io.littlehorse.common.proto.TaskCompleteOePb result = new io.littlehorse.common.proto.TaskCompleteOePb(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.threadRunNumber_ = threadRunNumber_;
      result.taskRunNumber_ = taskRunNumber_;
      result.taskRunPosition_ = taskRunPosition_;
      result.success_ = success_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.output_ = output_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.logOutput_ = logOutput_;
      result.nodeName_ = nodeName_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.littlehorse.common.proto.TaskCompleteOePb) {
        return mergeFrom((io.littlehorse.common.proto.TaskCompleteOePb)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.littlehorse.common.proto.TaskCompleteOePb other) {
      if (other == io.littlehorse.common.proto.TaskCompleteOePb.getDefaultInstance()) return this;
      if (other.getThreadRunNumber() != 0) {
        setThreadRunNumber(other.getThreadRunNumber());
      }
      if (other.getTaskRunNumber() != 0) {
        setTaskRunNumber(other.getTaskRunNumber());
      }
      if (other.getTaskRunPosition() != 0) {
        setTaskRunPosition(other.getTaskRunPosition());
      }
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (other.hasOutput()) {
        setOutput(other.getOutput());
      }
      if (other.hasLogOutput()) {
        setLogOutput(other.getLogOutput());
      }
      if (!other.getNodeName().isEmpty()) {
        nodeName_ = other.nodeName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.littlehorse.common.proto.TaskCompleteOePb parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.littlehorse.common.proto.TaskCompleteOePb) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int threadRunNumber_ ;
    /**
     * <code>int32 thread_run_number = 1;</code>
     * @return The threadRunNumber.
     */
    @java.lang.Override
    public int getThreadRunNumber() {
      return threadRunNumber_;
    }
    /**
     * <code>int32 thread_run_number = 1;</code>
     * @param value The threadRunNumber to set.
     * @return This builder for chaining.
     */
    public Builder setThreadRunNumber(int value) {
      
      threadRunNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 thread_run_number = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearThreadRunNumber() {
      
      threadRunNumber_ = 0;
      onChanged();
      return this;
    }

    private int taskRunNumber_ ;
    /**
     * <code>int32 task_run_number = 2;</code>
     * @return The taskRunNumber.
     */
    @java.lang.Override
    public int getTaskRunNumber() {
      return taskRunNumber_;
    }
    /**
     * <code>int32 task_run_number = 2;</code>
     * @param value The taskRunNumber to set.
     * @return This builder for chaining.
     */
    public Builder setTaskRunNumber(int value) {
      
      taskRunNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 task_run_number = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskRunNumber() {
      
      taskRunNumber_ = 0;
      onChanged();
      return this;
    }

    private int taskRunPosition_ ;
    /**
     * <code>int32 task_run_position = 3;</code>
     * @return The taskRunPosition.
     */
    @java.lang.Override
    public int getTaskRunPosition() {
      return taskRunPosition_;
    }
    /**
     * <code>int32 task_run_position = 3;</code>
     * @param value The taskRunPosition to set.
     * @return This builder for chaining.
     */
    public Builder setTaskRunPosition(int value) {
      
      taskRunPosition_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 task_run_position = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskRunPosition() {
      
      taskRunPosition_ = 0;
      onChanged();
      return this;
    }

    private boolean success_ ;
    /**
     * <code>bool success = 4;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 4;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString output_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes output = 5;</code>
     * @return Whether the output field is set.
     */
    @java.lang.Override
    public boolean hasOutput() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>bytes output = 5;</code>
     * @return The output.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getOutput() {
      return output_;
    }
    /**
     * <code>bytes output = 5;</code>
     * @param value The output to set.
     * @return This builder for chaining.
     */
    public Builder setOutput(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      output_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes output = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutput() {
      bitField0_ = (bitField0_ & ~0x00000001);
      output_ = getDefaultInstance().getOutput();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString logOutput_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes log_output = 6;</code>
     * @return Whether the logOutput field is set.
     */
    @java.lang.Override
    public boolean hasLogOutput() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>bytes log_output = 6;</code>
     * @return The logOutput.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLogOutput() {
      return logOutput_;
    }
    /**
     * <code>bytes log_output = 6;</code>
     * @param value The logOutput to set.
     * @return This builder for chaining.
     */
    public Builder setLogOutput(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      logOutput_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes log_output = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLogOutput() {
      bitField0_ = (bitField0_ & ~0x00000002);
      logOutput_ = getDefaultInstance().getLogOutput();
      onChanged();
      return this;
    }

    private java.lang.Object nodeName_ = "";
    /**
     * <code>string node_name = 7;</code>
     * @return The nodeName.
     */
    public java.lang.String getNodeName() {
      java.lang.Object ref = nodeName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string node_name = 7;</code>
     * @return The bytes for nodeName.
     */
    public com.google.protobuf.ByteString
        getNodeNameBytes() {
      java.lang.Object ref = nodeName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string node_name = 7;</code>
     * @param value The nodeName to set.
     * @return This builder for chaining.
     */
    public Builder setNodeName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nodeName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string node_name = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeName() {
      
      nodeName_ = getDefaultInstance().getNodeName();
      onChanged();
      return this;
    }
    /**
     * <code>string node_name = 7;</code>
     * @param value The bytes for nodeName to set.
     * @return This builder for chaining.
     */
    public Builder setNodeNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nodeName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lh_proto.TaskCompleteOePb)
  }

  // @@protoc_insertion_point(class_scope:lh_proto.TaskCompleteOePb)
  private static final io.littlehorse.common.proto.TaskCompleteOePb DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.littlehorse.common.proto.TaskCompleteOePb();
  }

  public static io.littlehorse.common.proto.TaskCompleteOePb getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TaskCompleteOePb>
      PARSER = new com.google.protobuf.AbstractParser<TaskCompleteOePb>() {
    @java.lang.Override
    public TaskCompleteOePb parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TaskCompleteOePb(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TaskCompleteOePb> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TaskCompleteOePb> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.littlehorse.common.proto.TaskCompleteOePb getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

