// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wf_run.proto

package io.littlehorse.common.proto;

public interface ThreadRunPbOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lh_proto.ThreadRunPb)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string wf_run_id = 1;</code>
   * @return The wfRunId.
   */
  java.lang.String getWfRunId();
  /**
   * <code>string wf_run_id = 1;</code>
   * @return The bytes for wfRunId.
   */
  com.google.protobuf.ByteString
      getWfRunIdBytes();

  /**
   * <code>int32 number = 2;</code>
   * @return The number.
   */
  int getNumber();

  /**
   * <code>.lh_proto.LHStatusPb status = 3;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.lh_proto.LHStatusPb status = 3;</code>
   * @return The status.
   */
  io.littlehorse.common.proto.LHStatusPb getStatus();

  /**
   * <code>string wf_spec_id = 4;</code>
   * @return The wfSpecId.
   */
  java.lang.String getWfSpecId();
  /**
   * <code>string wf_spec_id = 4;</code>
   * @return The bytes for wfSpecId.
   */
  com.google.protobuf.ByteString
      getWfSpecIdBytes();

  /**
   * <code>string thread_spec_name = 5;</code>
   * @return The threadSpecName.
   */
  java.lang.String getThreadSpecName();
  /**
   * <code>string thread_spec_name = 5;</code>
   * @return The bytes for threadSpecName.
   */
  com.google.protobuf.ByteString
      getThreadSpecNameBytes();

  /**
   * <code>.google.protobuf.Timestamp start_time = 6;</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <code>.google.protobuf.Timestamp start_time = 6;</code>
   * @return The startTime.
   */
  com.google.protobuf.Timestamp getStartTime();
  /**
   * <code>.google.protobuf.Timestamp start_time = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp end_time = 7;</code>
   * @return Whether the endTime field is set.
   */
  boolean hasEndTime();
  /**
   * <code>.google.protobuf.Timestamp end_time = 7;</code>
   * @return The endTime.
   */
  com.google.protobuf.Timestamp getEndTime();
  /**
   * <code>.google.protobuf.Timestamp end_time = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getEndTimeOrBuilder();

  /**
   * <code>int32 current_node_position = 8;</code>
   * @return The currentNodePosition.
   */
  int getCurrentNodePosition();

  /**
   * <code>string error_message = 9;</code>
   * @return Whether the errorMessage field is set.
   */
  boolean hasErrorMessage();
  /**
   * <code>string error_message = 9;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 9;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>.lh_proto.TaskResultCodePb result_code = 10;</code>
   * @return Whether the resultCode field is set.
   */
  boolean hasResultCode();
  /**
   * <code>.lh_proto.TaskResultCodePb result_code = 10;</code>
   * @return The enum numeric value on the wire for resultCode.
   */
  int getResultCodeValue();
  /**
   * <code>.lh_proto.TaskResultCodePb result_code = 10;</code>
   * @return The resultCode.
   */
  io.littlehorse.common.proto.TaskResultCodePb getResultCode();

  /**
   * <code>repeated int32 child_thread_ids = 11;</code>
   * @return A list containing the childThreadIds.
   */
  java.util.List<java.lang.Integer> getChildThreadIdsList();
  /**
   * <code>repeated int32 child_thread_ids = 11;</code>
   * @return The count of childThreadIds.
   */
  int getChildThreadIdsCount();
  /**
   * <code>repeated int32 child_thread_ids = 11;</code>
   * @param index The index of the element to return.
   * @return The childThreadIds at the given index.
   */
  int getChildThreadIds(int index);

  /**
   * <code>int32 parent_thread_id = 12;</code>
   * @return Whether the parentThreadId field is set.
   */
  boolean hasParentThreadId();
  /**
   * <code>int32 parent_thread_id = 12;</code>
   * @return The parentThreadId.
   */
  int getParentThreadId();

  /**
   * <code>repeated .lh_proto.ThreadHaltReasonPb halt_reasons = 13;</code>
   */
  java.util.List<io.littlehorse.common.proto.ThreadHaltReasonPb> 
      getHaltReasonsList();
  /**
   * <code>repeated .lh_proto.ThreadHaltReasonPb halt_reasons = 13;</code>
   */
  io.littlehorse.common.proto.ThreadHaltReasonPb getHaltReasons(int index);
  /**
   * <code>repeated .lh_proto.ThreadHaltReasonPb halt_reasons = 13;</code>
   */
  int getHaltReasonsCount();
  /**
   * <code>repeated .lh_proto.ThreadHaltReasonPb halt_reasons = 13;</code>
   */
  java.util.List<? extends io.littlehorse.common.proto.ThreadHaltReasonPbOrBuilder> 
      getHaltReasonsOrBuilderList();
  /**
   * <code>repeated .lh_proto.ThreadHaltReasonPb halt_reasons = 13;</code>
   */
  io.littlehorse.common.proto.ThreadHaltReasonPbOrBuilder getHaltReasonsOrBuilder(
      int index);

  /**
   * <code>string interrupt_trigger_id = 14;</code>
   * @return Whether the interruptTriggerId field is set.
   */
  boolean hasInterruptTriggerId();
  /**
   * <code>string interrupt_trigger_id = 14;</code>
   * @return The interruptTriggerId.
   */
  java.lang.String getInterruptTriggerId();
  /**
   * <code>string interrupt_trigger_id = 14;</code>
   * @return The bytes for interruptTriggerId.
   */
  com.google.protobuf.ByteString
      getInterruptTriggerIdBytes();

  /**
   * <code>.lh_proto.FailureBeingHandledPb failure_being_handled = 15;</code>
   * @return Whether the failureBeingHandled field is set.
   */
  boolean hasFailureBeingHandled();
  /**
   * <code>.lh_proto.FailureBeingHandledPb failure_being_handled = 15;</code>
   * @return The failureBeingHandled.
   */
  io.littlehorse.common.proto.FailureBeingHandledPb getFailureBeingHandled();
  /**
   * <code>.lh_proto.FailureBeingHandledPb failure_being_handled = 15;</code>
   */
  io.littlehorse.common.proto.FailureBeingHandledPbOrBuilder getFailureBeingHandledOrBuilder();
}
