name: Bug Report
description: Allows to report any bug or unexpected functionality in LittleHorse.
type: "bug"
projects: ["littlehorse-enterprises/1"]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: "Anything that makes this issue complete."
      placeholder: |
        Go to ...
        Click on ....
        Scroll down to ....
        See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
  - type: checkboxes
    id: components
    attributes:
      label: Which components does this bug affect?
      description: You may select more than one.
      options:
        - label: Dashboard
        - label: Kernel
        - label: Java SDK
        - label: Python SDK
        - label: Go SDK
        - label: Dotnet SDK
        - label: LH Control
        - label: LH Tests Utils
  - type: input
    id: version
    attributes:
      label: LittleHorse Version
      description: A version of LittleHorse that this bug occurred on
      placeholder: "v0.13.2"
  - type: textarea
    id: documentation
    attributes:
      label: What documentation changes are necessary when this bug is fixed?
    validations:
      required: true
