name: Enhancement
description: Minor change, refactor or enhancement
labels: ["enhancement"]
projects: ["littlehorse-enterprises/1"]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Describe the context and any relevant information about this enhancement.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Anything that makes this issue complete.
      value: |
        **Scenario** [the name for the behavior that will be described]
        **Given** [the beginning state of the scenario]
        **When** [specific action that the user makes]
        **Then** [the outcome of the action in **When**]
        **And** [used to continue any of three previous statements]
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Out of Scope
      description: Allows to define what is within the scope of the user story and what's not.
  - type: checkboxes
    id: components
    attributes:
      label: Components
      description: You may select one or more.
      options:
        - label: Dashboard
        - label: Server
        - label: Python SDK
        - label: Go SDK
        - label: Java SDK
        - label: C# SDK
        - label: LH Control
        - label: LH Tests Utils
