name: Enhancement
description: Feature, minor change, or enhancement.
type: "feature"
projects: ["littlehorse-enterprises/1"]
body:
  - type: textarea
    id: background
    attributes:
      label: Background
      description: Describe the background of this change. What inspired this enhancement?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Enhancement Proposal
      description: Describe your proposed enhancement
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Anything that makes this issue complete.
      value: |
        **Scenario** [the name for the behavior that will be described]
        **Given** [the beginning state of the scenario]
        **When** [specific action that the user makes]
        **Then** [the outcome of the action in **When**]
        **And** [used to continue any of three previous statements]
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Out of Scope
      description: Allows to define what is within the scope of the user story and what's not.
  - type: checkboxes
    id: components
    attributes:
      label: Which components does this enhancement affect?
      description: You may select more than one.
      options:
        - Dashboard
        - Kernel
        - sdk-python
        - sdk-go
        - sdk-java
        - sdk-dotnet
        - lhctl
        - LH Tests Utils
  - type: textarea
    id: documentation
    attributes:
      label: What documentation changes are necessary to complete this enhancement?
    validations:
      required: true
