name: Feature Request
description: Suggest a feature, minor change, or enhancement to LittleHorse.
type: "feature"
projects: ["littlehorse-enterprises/1"]
body:
  - type: textarea
    id: background
    attributes:
      label: Background
      description: Describe the background of this change. What inspired this enhancement?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe your proposed feature, minor change, or enhancement
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Anything that makes this issue complete.
      placeholder: |
        **Scenario** [the name for the behavior that will be described]
        **Given** [the beginning state of the scenario]
        **When** [specific action that the user makes]
        **Then** [the outcome of the action in **When**]
        **And** [used to continue any of three previous statements]
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Out of Scope
      description: Allows to define what is within the scope of the enhancement and what's not.
  - type: checkboxes
    id: components
    attributes:
      label: Affected Components
      description: Which components does this bug affect? You may select more than one.
      options:
        - label: Dashboard
        - label: Kernel
        - label: Java SDK
        - label: Python SDK
        - label: Go SDK
        - label: .NET SDK
        - label: LH Control
        - label: LH Tests Utils
  - type: textarea
    id: documentation
    attributes:
      label: Documentation
      description: What documentation changes are necessary when this bug is fixed?
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature here.
