name: 🌟 Feature Request
description: Suggest a feature, minor change, or enhancement to LittleHorse.
type: "feature"
projects: ["littlehorse-enterprises/1"]
body:
  - type: textarea
    id: background
    attributes:
      label: Background
      description: Describe the background of this change. What inspired this enhancement?
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe your proposed feature, minor change, or enhancement
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Anything that makes this issue complete.
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Out of Scope
      description: Allows to define what is within the scope of the enhancement and what's not.
  - type: checkboxes
    id: components
    attributes:
      label: Affected Components
      description: Which components does this bug affect? You may select more than one.
      options:
        - label: Kernel (/server)
        - label: LH Control (/lhctl)
        - label: Dashboard
        - label: Java SDK
        - label: Python SDK
        - label: Go SDK
        - label: .NET SDK
        - label: LH Tests Utils
  - type: textarea
    id: documentation
    attributes:
      label: Documentation
      description: "Include ideas about or references to documentation changes that should be made when this feature is implemented."
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any additional information or comments about the bug here.
