name: Technical Debt
description: Technical Debt
labels: ["tech-debt", "enhancement"]
projects: ["littlehorse-enterprises/1"]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: About this tech debt.
    validations:
      required: true
  - type: dropdown
    id: value
    attributes:
      label: Value
      options:
        - High
        - Low
    validations:
      required: true
  - type: dropdown
    id: effort
    attributes:
      label: Effort
      options:
        - High
        - Low
    validations:
      required: true
  - type: textarea
    id: current-state
    attributes:
      label: Current State and Pains
      description: What is happening now?, Why is it painful?.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution and Benefits
      description: What is the proposals?. List the benefits.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Anything that makes this issue complete.
      value: |
        **Scenario** [the name for the behavior that will be described]
        **Given** [the beginning state of the scenario]
        **When** [specific action that the user makes]
        **Then** [the outcome of the action in **When**]
        **And** [used to continue any of three previous statements]
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
  - type: dropdown
    id: components
    attributes:
      label: Components
      description: Please select all the affected components.
      multiple: true
      options:
        - Dashboard
        - Server
        - Python SDK
        - Go SDK
        - Java SDK
        - C# SDK
        - LH Control
        - LH Tests Utils
