name: User Story
description: New feature
labels: ["feature"]
projects: ["littlehorse-enterprises/1"]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Describe the context and any relevant information about this enhancement.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: The User Story.
      value: |
        **As a** [description of user]
        **I want to** [functionality]
        **So that** [benefit]
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Anything that makes this issue complete.
      value: |
        **Scenario** [the name for the behavior that will be described]
        **Given** [the beginning state of the scenario]
        **When** [specific action that the user makes]
        **Then** [the outcome of the action in **When**]
        **And** [used to continue any of three previous statements]
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Out of Scope
      description: Allows to define what is within the scope of the user story and what's not.
  - type: textarea
    id: technical-context
    attributes:
      label: Technical Context
      description: Here we need to specify if there are any technical constraints that might guide the implementation of the user story.
  - type: dropdown
    id: components
    attributes:
      label: Components
      description: Please select all the affected components.
      multiple: true
      options:
        - Dashboard
        - Server
        - Python SDK
        - Go SDK
        - Java SDK
        - C# SDK
        - LH Control
        - LH Tests Utils
