#!/bin/bash
LHORSE_KAFKA_GROUP_ID=server LHORSE_KAFKA_GROUP_IID=server2 LHORSE_EXPOSED_PORT=5001 LHORSE_ADVERTISED_PORT=5001 LHORSE_KAFKA_STREAMS_STATE_DIR=/tmp/kafkaStateTwo gradle run --args server
