// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v6.32.1
// source: metrics.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Timestamp } from "./google/protobuf/timestamp";
import { TaskDefId, TenantId, UserTaskDefId, WfSpecId } from "./object_id";

/**
 * Identifies a metrics window for a workflow/task/user-task object.
 * `window_start` marks the window start; `tenant_id` is optional.
 */
export interface MetricWindowId {
  id?:
    | { $case: "wfSpecId"; value: WfSpecId }
    | { $case: "taskDefId"; value: TaskDefId }
    | { $case: "userTaskDefId"; value: UserTaskDefId }
    | undefined;
  /** Tenant for this window (optional). */
  tenantId?:
    | TenantId
    | undefined;
  /** Start time of the window. */
  windowStart: string | undefined;
}

/**
 * Aggregate counts and latency stats for a metric window. Use
 * `total_latency_ms / count` to compute average latency.
 */
export interface CountAndTiming {
  /** Number of events. */
  count: number;
  /** Minimum latency in ms. */
  minLatencyMs: number;
  /** Maximum latency in ms. */
  maxLatencyMs: number;
  /** Sum of all latencies in ms. */
  totalLatencyMs: number;
}

/**
 * Aggregated metrics for a workflow or task within a time window.
 * Only one of `workflow` or `task` will be populated.
 */
export interface MetricWindow {
  /** Window identifier. */
  id: MetricWindowId | undefined;
  metric?: { $case: "workflow"; value: WfMetrics } | { $case: "task"; value: TaskMetrics } | undefined;
}

/** Workflow-level aggregates for lifecycle transitions; fields are `CountAndTiming`. */
export interface WfMetrics {
  /** WfRun started. */
  started:
    | CountAndTiming
    | undefined;
  /** Running → Completed. */
  runningToCompleted:
    | CountAndTiming
    | undefined;
  /** Running → Error. */
  runningToError:
    | CountAndTiming
    | undefined;
  /** Running → Exception. */
  runningToException:
    | CountAndTiming
    | undefined;
  /** Running → Halting. */
  runningToHalting:
    | CountAndTiming
    | undefined;
  /** Halting → Halted. */
  haltingToHalted:
    | CountAndTiming
    | undefined;
  /** Halted → Running. */
  haltedToRunning:
    | CountAndTiming
    | undefined;
  /** Halted → Running. */
  runningToHalted: CountAndTiming | undefined;
}

/** Task-level aggregates for task lifecycle transitions; fields are `CountAndTiming`. */
export interface TaskMetrics {
  /** Created → Completed. */
  taskrunCreatedToCompleted:
    | CountAndTiming
    | undefined;
  /** Created → Error. */
  taskrunCreatedToError:
    | CountAndTiming
    | undefined;
  /** Created → Exception. */
  taskrunCreatedToException:
    | CountAndTiming
    | undefined;
  /** Pending → Scheduled. */
  taskattemptPendingToScheduled:
    | CountAndTiming
    | undefined;
  /** Scheduled → Running. */
  taskattemptScheduledToRunning:
    | CountAndTiming
    | undefined;
  /** Running → Error. */
  taskattemptRunningToError:
    | CountAndTiming
    | undefined;
  /** Running → Success. */
  taskattemptRunningToSuccess:
    | CountAndTiming
    | undefined;
  /** Running → Exception. */
  taskattemptRunningToException: CountAndTiming | undefined;
}

export interface ListWfMetricsRequest {
  wfSpec: WfSpecId | undefined;
  windowStart?: string | undefined;
  windowEnd?: string | undefined;
}

export interface ListTaskMetricsRequest {
  taskDef: TaskDefId | undefined;
  windowStart?: string | undefined;
  windowEnd?: string | undefined;
}

export interface MetricsList {
  windows: MetricWindow[];
}

function createBaseMetricWindowId(): MetricWindowId {
  return { id: undefined, tenantId: undefined, windowStart: undefined };
}

export const MetricWindowId = {
  encode(message: MetricWindowId, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    switch (message.id?.$case) {
      case "wfSpecId":
        WfSpecId.encode(message.id.value, writer.uint32(10).fork()).ldelim();
        break;
      case "taskDefId":
        TaskDefId.encode(message.id.value, writer.uint32(18).fork()).ldelim();
        break;
      case "userTaskDefId":
        UserTaskDefId.encode(message.id.value, writer.uint32(26).fork()).ldelim();
        break;
    }
    if (message.tenantId !== undefined) {
      TenantId.encode(message.tenantId, writer.uint32(50).fork()).ldelim();
    }
    if (message.windowStart !== undefined) {
      Timestamp.encode(toTimestamp(message.windowStart), writer.uint32(58).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MetricWindowId {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMetricWindowId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = { $case: "wfSpecId", value: WfSpecId.decode(reader, reader.uint32()) };
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.id = { $case: "taskDefId", value: TaskDefId.decode(reader, reader.uint32()) };
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.id = { $case: "userTaskDefId", value: UserTaskDefId.decode(reader, reader.uint32()) };
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.tenantId = TenantId.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.windowStart = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MetricWindowId {
    return {
      id: isSet(object.wfSpecId)
        ? { $case: "wfSpecId", value: WfSpecId.fromJSON(object.wfSpecId) }
        : isSet(object.taskDefId)
        ? { $case: "taskDefId", value: TaskDefId.fromJSON(object.taskDefId) }
        : isSet(object.userTaskDefId)
        ? { $case: "userTaskDefId", value: UserTaskDefId.fromJSON(object.userTaskDefId) }
        : undefined,
      tenantId: isSet(object.tenantId) ? TenantId.fromJSON(object.tenantId) : undefined,
      windowStart: isSet(object.windowStart) ? globalThis.String(object.windowStart) : undefined,
    };
  },

  toJSON(message: MetricWindowId): unknown {
    const obj: any = {};
    if (message.id?.$case === "wfSpecId") {
      obj.wfSpecId = WfSpecId.toJSON(message.id.value);
    }
    if (message.id?.$case === "taskDefId") {
      obj.taskDefId = TaskDefId.toJSON(message.id.value);
    }
    if (message.id?.$case === "userTaskDefId") {
      obj.userTaskDefId = UserTaskDefId.toJSON(message.id.value);
    }
    if (message.tenantId !== undefined) {
      obj.tenantId = TenantId.toJSON(message.tenantId);
    }
    if (message.windowStart !== undefined) {
      obj.windowStart = message.windowStart;
    }
    return obj;
  },

  create(base?: DeepPartial<MetricWindowId>): MetricWindowId {
    return MetricWindowId.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MetricWindowId>): MetricWindowId {
    const message = createBaseMetricWindowId();
    if (object.id?.$case === "wfSpecId" && object.id?.value !== undefined && object.id?.value !== null) {
      message.id = { $case: "wfSpecId", value: WfSpecId.fromPartial(object.id.value) };
    }
    if (object.id?.$case === "taskDefId" && object.id?.value !== undefined && object.id?.value !== null) {
      message.id = { $case: "taskDefId", value: TaskDefId.fromPartial(object.id.value) };
    }
    if (object.id?.$case === "userTaskDefId" && object.id?.value !== undefined && object.id?.value !== null) {
      message.id = { $case: "userTaskDefId", value: UserTaskDefId.fromPartial(object.id.value) };
    }
    message.tenantId = (object.tenantId !== undefined && object.tenantId !== null)
      ? TenantId.fromPartial(object.tenantId)
      : undefined;
    message.windowStart = object.windowStart ?? undefined;
    return message;
  },
};

function createBaseCountAndTiming(): CountAndTiming {
  return { count: 0, minLatencyMs: 0, maxLatencyMs: 0, totalLatencyMs: 0 };
}

export const CountAndTiming = {
  encode(message: CountAndTiming, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.count !== 0) {
      writer.uint32(8).int32(message.count);
    }
    if (message.minLatencyMs !== 0) {
      writer.uint32(16).int64(message.minLatencyMs);
    }
    if (message.maxLatencyMs !== 0) {
      writer.uint32(24).int64(message.maxLatencyMs);
    }
    if (message.totalLatencyMs !== 0) {
      writer.uint32(32).int64(message.totalLatencyMs);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CountAndTiming {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCountAndTiming();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.count = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.minLatencyMs = longToNumber(reader.int64() as Long);
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.maxLatencyMs = longToNumber(reader.int64() as Long);
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.totalLatencyMs = longToNumber(reader.int64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CountAndTiming {
    return {
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
      minLatencyMs: isSet(object.minLatencyMs) ? globalThis.Number(object.minLatencyMs) : 0,
      maxLatencyMs: isSet(object.maxLatencyMs) ? globalThis.Number(object.maxLatencyMs) : 0,
      totalLatencyMs: isSet(object.totalLatencyMs) ? globalThis.Number(object.totalLatencyMs) : 0,
    };
  },

  toJSON(message: CountAndTiming): unknown {
    const obj: any = {};
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    if (message.minLatencyMs !== 0) {
      obj.minLatencyMs = Math.round(message.minLatencyMs);
    }
    if (message.maxLatencyMs !== 0) {
      obj.maxLatencyMs = Math.round(message.maxLatencyMs);
    }
    if (message.totalLatencyMs !== 0) {
      obj.totalLatencyMs = Math.round(message.totalLatencyMs);
    }
    return obj;
  },

  create(base?: DeepPartial<CountAndTiming>): CountAndTiming {
    return CountAndTiming.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CountAndTiming>): CountAndTiming {
    const message = createBaseCountAndTiming();
    message.count = object.count ?? 0;
    message.minLatencyMs = object.minLatencyMs ?? 0;
    message.maxLatencyMs = object.maxLatencyMs ?? 0;
    message.totalLatencyMs = object.totalLatencyMs ?? 0;
    return message;
  },
};

function createBaseMetricWindow(): MetricWindow {
  return { id: undefined, metric: undefined };
}

export const MetricWindow = {
  encode(message: MetricWindow, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== undefined) {
      MetricWindowId.encode(message.id, writer.uint32(10).fork()).ldelim();
    }
    switch (message.metric?.$case) {
      case "workflow":
        WfMetrics.encode(message.metric.value, writer.uint32(18).fork()).ldelim();
        break;
      case "task":
        TaskMetrics.encode(message.metric.value, writer.uint32(26).fork()).ldelim();
        break;
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MetricWindow {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMetricWindow();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = MetricWindowId.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.metric = { $case: "workflow", value: WfMetrics.decode(reader, reader.uint32()) };
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.metric = { $case: "task", value: TaskMetrics.decode(reader, reader.uint32()) };
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MetricWindow {
    return {
      id: isSet(object.id) ? MetricWindowId.fromJSON(object.id) : undefined,
      metric: isSet(object.workflow)
        ? { $case: "workflow", value: WfMetrics.fromJSON(object.workflow) }
        : isSet(object.task)
        ? { $case: "task", value: TaskMetrics.fromJSON(object.task) }
        : undefined,
    };
  },

  toJSON(message: MetricWindow): unknown {
    const obj: any = {};
    if (message.id !== undefined) {
      obj.id = MetricWindowId.toJSON(message.id);
    }
    if (message.metric?.$case === "workflow") {
      obj.workflow = WfMetrics.toJSON(message.metric.value);
    }
    if (message.metric?.$case === "task") {
      obj.task = TaskMetrics.toJSON(message.metric.value);
    }
    return obj;
  },

  create(base?: DeepPartial<MetricWindow>): MetricWindow {
    return MetricWindow.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MetricWindow>): MetricWindow {
    const message = createBaseMetricWindow();
    message.id = (object.id !== undefined && object.id !== null) ? MetricWindowId.fromPartial(object.id) : undefined;
    if (object.metric?.$case === "workflow" && object.metric?.value !== undefined && object.metric?.value !== null) {
      message.metric = { $case: "workflow", value: WfMetrics.fromPartial(object.metric.value) };
    }
    if (object.metric?.$case === "task" && object.metric?.value !== undefined && object.metric?.value !== null) {
      message.metric = { $case: "task", value: TaskMetrics.fromPartial(object.metric.value) };
    }
    return message;
  },
};

function createBaseWfMetrics(): WfMetrics {
  return {
    started: undefined,
    runningToCompleted: undefined,
    runningToError: undefined,
    runningToException: undefined,
    runningToHalting: undefined,
    haltingToHalted: undefined,
    haltedToRunning: undefined,
    runningToHalted: undefined,
  };
}

export const WfMetrics = {
  encode(message: WfMetrics, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.started !== undefined) {
      CountAndTiming.encode(message.started, writer.uint32(10).fork()).ldelim();
    }
    if (message.runningToCompleted !== undefined) {
      CountAndTiming.encode(message.runningToCompleted, writer.uint32(18).fork()).ldelim();
    }
    if (message.runningToError !== undefined) {
      CountAndTiming.encode(message.runningToError, writer.uint32(26).fork()).ldelim();
    }
    if (message.runningToException !== undefined) {
      CountAndTiming.encode(message.runningToException, writer.uint32(34).fork()).ldelim();
    }
    if (message.runningToHalting !== undefined) {
      CountAndTiming.encode(message.runningToHalting, writer.uint32(42).fork()).ldelim();
    }
    if (message.haltingToHalted !== undefined) {
      CountAndTiming.encode(message.haltingToHalted, writer.uint32(50).fork()).ldelim();
    }
    if (message.haltedToRunning !== undefined) {
      CountAndTiming.encode(message.haltedToRunning, writer.uint32(58).fork()).ldelim();
    }
    if (message.runningToHalted !== undefined) {
      CountAndTiming.encode(message.runningToHalted, writer.uint32(66).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): WfMetrics {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWfMetrics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.started = CountAndTiming.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.runningToCompleted = CountAndTiming.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.runningToError = CountAndTiming.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.runningToException = CountAndTiming.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.runningToHalting = CountAndTiming.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.haltingToHalted = CountAndTiming.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.haltedToRunning = CountAndTiming.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.runningToHalted = CountAndTiming.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WfMetrics {
    return {
      started: isSet(object.started) ? CountAndTiming.fromJSON(object.started) : undefined,
      runningToCompleted: isSet(object.runningToCompleted)
        ? CountAndTiming.fromJSON(object.runningToCompleted)
        : undefined,
      runningToError: isSet(object.runningToError) ? CountAndTiming.fromJSON(object.runningToError) : undefined,
      runningToException: isSet(object.runningToException)
        ? CountAndTiming.fromJSON(object.runningToException)
        : undefined,
      runningToHalting: isSet(object.runningToHalting) ? CountAndTiming.fromJSON(object.runningToHalting) : undefined,
      haltingToHalted: isSet(object.haltingToHalted) ? CountAndTiming.fromJSON(object.haltingToHalted) : undefined,
      haltedToRunning: isSet(object.haltedToRunning) ? CountAndTiming.fromJSON(object.haltedToRunning) : undefined,
      runningToHalted: isSet(object.runningToHalted) ? CountAndTiming.fromJSON(object.runningToHalted) : undefined,
    };
  },

  toJSON(message: WfMetrics): unknown {
    const obj: any = {};
    if (message.started !== undefined) {
      obj.started = CountAndTiming.toJSON(message.started);
    }
    if (message.runningToCompleted !== undefined) {
      obj.runningToCompleted = CountAndTiming.toJSON(message.runningToCompleted);
    }
    if (message.runningToError !== undefined) {
      obj.runningToError = CountAndTiming.toJSON(message.runningToError);
    }
    if (message.runningToException !== undefined) {
      obj.runningToException = CountAndTiming.toJSON(message.runningToException);
    }
    if (message.runningToHalting !== undefined) {
      obj.runningToHalting = CountAndTiming.toJSON(message.runningToHalting);
    }
    if (message.haltingToHalted !== undefined) {
      obj.haltingToHalted = CountAndTiming.toJSON(message.haltingToHalted);
    }
    if (message.haltedToRunning !== undefined) {
      obj.haltedToRunning = CountAndTiming.toJSON(message.haltedToRunning);
    }
    if (message.runningToHalted !== undefined) {
      obj.runningToHalted = CountAndTiming.toJSON(message.runningToHalted);
    }
    return obj;
  },

  create(base?: DeepPartial<WfMetrics>): WfMetrics {
    return WfMetrics.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WfMetrics>): WfMetrics {
    const message = createBaseWfMetrics();
    message.started = (object.started !== undefined && object.started !== null)
      ? CountAndTiming.fromPartial(object.started)
      : undefined;
    message.runningToCompleted = (object.runningToCompleted !== undefined && object.runningToCompleted !== null)
      ? CountAndTiming.fromPartial(object.runningToCompleted)
      : undefined;
    message.runningToError = (object.runningToError !== undefined && object.runningToError !== null)
      ? CountAndTiming.fromPartial(object.runningToError)
      : undefined;
    message.runningToException = (object.runningToException !== undefined && object.runningToException !== null)
      ? CountAndTiming.fromPartial(object.runningToException)
      : undefined;
    message.runningToHalting = (object.runningToHalting !== undefined && object.runningToHalting !== null)
      ? CountAndTiming.fromPartial(object.runningToHalting)
      : undefined;
    message.haltingToHalted = (object.haltingToHalted !== undefined && object.haltingToHalted !== null)
      ? CountAndTiming.fromPartial(object.haltingToHalted)
      : undefined;
    message.haltedToRunning = (object.haltedToRunning !== undefined && object.haltedToRunning !== null)
      ? CountAndTiming.fromPartial(object.haltedToRunning)
      : undefined;
    message.runningToHalted = (object.runningToHalted !== undefined && object.runningToHalted !== null)
      ? CountAndTiming.fromPartial(object.runningToHalted)
      : undefined;
    return message;
  },
};

function createBaseTaskMetrics(): TaskMetrics {
  return {
    taskrunCreatedToCompleted: undefined,
    taskrunCreatedToError: undefined,
    taskrunCreatedToException: undefined,
    taskattemptPendingToScheduled: undefined,
    taskattemptScheduledToRunning: undefined,
    taskattemptRunningToError: undefined,
    taskattemptRunningToSuccess: undefined,
    taskattemptRunningToException: undefined,
  };
}

export const TaskMetrics = {
  encode(message: TaskMetrics, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.taskrunCreatedToCompleted !== undefined) {
      CountAndTiming.encode(message.taskrunCreatedToCompleted, writer.uint32(10).fork()).ldelim();
    }
    if (message.taskrunCreatedToError !== undefined) {
      CountAndTiming.encode(message.taskrunCreatedToError, writer.uint32(18).fork()).ldelim();
    }
    if (message.taskrunCreatedToException !== undefined) {
      CountAndTiming.encode(message.taskrunCreatedToException, writer.uint32(26).fork()).ldelim();
    }
    if (message.taskattemptPendingToScheduled !== undefined) {
      CountAndTiming.encode(message.taskattemptPendingToScheduled, writer.uint32(34).fork()).ldelim();
    }
    if (message.taskattemptScheduledToRunning !== undefined) {
      CountAndTiming.encode(message.taskattemptScheduledToRunning, writer.uint32(42).fork()).ldelim();
    }
    if (message.taskattemptRunningToError !== undefined) {
      CountAndTiming.encode(message.taskattemptRunningToError, writer.uint32(50).fork()).ldelim();
    }
    if (message.taskattemptRunningToSuccess !== undefined) {
      CountAndTiming.encode(message.taskattemptRunningToSuccess, writer.uint32(58).fork()).ldelim();
    }
    if (message.taskattemptRunningToException !== undefined) {
      CountAndTiming.encode(message.taskattemptRunningToException, writer.uint32(66).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TaskMetrics {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskMetrics();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.taskrunCreatedToCompleted = CountAndTiming.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.taskrunCreatedToError = CountAndTiming.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.taskrunCreatedToException = CountAndTiming.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.taskattemptPendingToScheduled = CountAndTiming.decode(reader, reader.uint32());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.taskattemptScheduledToRunning = CountAndTiming.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.taskattemptRunningToError = CountAndTiming.decode(reader, reader.uint32());
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.taskattemptRunningToSuccess = CountAndTiming.decode(reader, reader.uint32());
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.taskattemptRunningToException = CountAndTiming.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskMetrics {
    return {
      taskrunCreatedToCompleted: isSet(object.taskrunCreatedToCompleted)
        ? CountAndTiming.fromJSON(object.taskrunCreatedToCompleted)
        : undefined,
      taskrunCreatedToError: isSet(object.taskrunCreatedToError)
        ? CountAndTiming.fromJSON(object.taskrunCreatedToError)
        : undefined,
      taskrunCreatedToException: isSet(object.taskrunCreatedToException)
        ? CountAndTiming.fromJSON(object.taskrunCreatedToException)
        : undefined,
      taskattemptPendingToScheduled: isSet(object.taskattemptPendingToScheduled)
        ? CountAndTiming.fromJSON(object.taskattemptPendingToScheduled)
        : undefined,
      taskattemptScheduledToRunning: isSet(object.taskattemptScheduledToRunning)
        ? CountAndTiming.fromJSON(object.taskattemptScheduledToRunning)
        : undefined,
      taskattemptRunningToError: isSet(object.taskattemptRunningToError)
        ? CountAndTiming.fromJSON(object.taskattemptRunningToError)
        : undefined,
      taskattemptRunningToSuccess: isSet(object.taskattemptRunningToSuccess)
        ? CountAndTiming.fromJSON(object.taskattemptRunningToSuccess)
        : undefined,
      taskattemptRunningToException: isSet(object.taskattemptRunningToException)
        ? CountAndTiming.fromJSON(object.taskattemptRunningToException)
        : undefined,
    };
  },

  toJSON(message: TaskMetrics): unknown {
    const obj: any = {};
    if (message.taskrunCreatedToCompleted !== undefined) {
      obj.taskrunCreatedToCompleted = CountAndTiming.toJSON(message.taskrunCreatedToCompleted);
    }
    if (message.taskrunCreatedToError !== undefined) {
      obj.taskrunCreatedToError = CountAndTiming.toJSON(message.taskrunCreatedToError);
    }
    if (message.taskrunCreatedToException !== undefined) {
      obj.taskrunCreatedToException = CountAndTiming.toJSON(message.taskrunCreatedToException);
    }
    if (message.taskattemptPendingToScheduled !== undefined) {
      obj.taskattemptPendingToScheduled = CountAndTiming.toJSON(message.taskattemptPendingToScheduled);
    }
    if (message.taskattemptScheduledToRunning !== undefined) {
      obj.taskattemptScheduledToRunning = CountAndTiming.toJSON(message.taskattemptScheduledToRunning);
    }
    if (message.taskattemptRunningToError !== undefined) {
      obj.taskattemptRunningToError = CountAndTiming.toJSON(message.taskattemptRunningToError);
    }
    if (message.taskattemptRunningToSuccess !== undefined) {
      obj.taskattemptRunningToSuccess = CountAndTiming.toJSON(message.taskattemptRunningToSuccess);
    }
    if (message.taskattemptRunningToException !== undefined) {
      obj.taskattemptRunningToException = CountAndTiming.toJSON(message.taskattemptRunningToException);
    }
    return obj;
  },

  create(base?: DeepPartial<TaskMetrics>): TaskMetrics {
    return TaskMetrics.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TaskMetrics>): TaskMetrics {
    const message = createBaseTaskMetrics();
    message.taskrunCreatedToCompleted =
      (object.taskrunCreatedToCompleted !== undefined && object.taskrunCreatedToCompleted !== null)
        ? CountAndTiming.fromPartial(object.taskrunCreatedToCompleted)
        : undefined;
    message.taskrunCreatedToError =
      (object.taskrunCreatedToError !== undefined && object.taskrunCreatedToError !== null)
        ? CountAndTiming.fromPartial(object.taskrunCreatedToError)
        : undefined;
    message.taskrunCreatedToException =
      (object.taskrunCreatedToException !== undefined && object.taskrunCreatedToException !== null)
        ? CountAndTiming.fromPartial(object.taskrunCreatedToException)
        : undefined;
    message.taskattemptPendingToScheduled =
      (object.taskattemptPendingToScheduled !== undefined && object.taskattemptPendingToScheduled !== null)
        ? CountAndTiming.fromPartial(object.taskattemptPendingToScheduled)
        : undefined;
    message.taskattemptScheduledToRunning =
      (object.taskattemptScheduledToRunning !== undefined && object.taskattemptScheduledToRunning !== null)
        ? CountAndTiming.fromPartial(object.taskattemptScheduledToRunning)
        : undefined;
    message.taskattemptRunningToError =
      (object.taskattemptRunningToError !== undefined && object.taskattemptRunningToError !== null)
        ? CountAndTiming.fromPartial(object.taskattemptRunningToError)
        : undefined;
    message.taskattemptRunningToSuccess =
      (object.taskattemptRunningToSuccess !== undefined && object.taskattemptRunningToSuccess !== null)
        ? CountAndTiming.fromPartial(object.taskattemptRunningToSuccess)
        : undefined;
    message.taskattemptRunningToException =
      (object.taskattemptRunningToException !== undefined && object.taskattemptRunningToException !== null)
        ? CountAndTiming.fromPartial(object.taskattemptRunningToException)
        : undefined;
    return message;
  },
};

function createBaseListWfMetricsRequest(): ListWfMetricsRequest {
  return { wfSpec: undefined, windowStart: undefined, windowEnd: undefined };
}

export const ListWfMetricsRequest = {
  encode(message: ListWfMetricsRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.wfSpec !== undefined) {
      WfSpecId.encode(message.wfSpec, writer.uint32(10).fork()).ldelim();
    }
    if (message.windowStart !== undefined) {
      Timestamp.encode(toTimestamp(message.windowStart), writer.uint32(18).fork()).ldelim();
    }
    if (message.windowEnd !== undefined) {
      Timestamp.encode(toTimestamp(message.windowEnd), writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListWfMetricsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListWfMetricsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.wfSpec = WfSpecId.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.windowStart = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.windowEnd = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListWfMetricsRequest {
    return {
      wfSpec: isSet(object.wfSpec) ? WfSpecId.fromJSON(object.wfSpec) : undefined,
      windowStart: isSet(object.windowStart) ? globalThis.String(object.windowStart) : undefined,
      windowEnd: isSet(object.windowEnd) ? globalThis.String(object.windowEnd) : undefined,
    };
  },

  toJSON(message: ListWfMetricsRequest): unknown {
    const obj: any = {};
    if (message.wfSpec !== undefined) {
      obj.wfSpec = WfSpecId.toJSON(message.wfSpec);
    }
    if (message.windowStart !== undefined) {
      obj.windowStart = message.windowStart;
    }
    if (message.windowEnd !== undefined) {
      obj.windowEnd = message.windowEnd;
    }
    return obj;
  },

  create(base?: DeepPartial<ListWfMetricsRequest>): ListWfMetricsRequest {
    return ListWfMetricsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListWfMetricsRequest>): ListWfMetricsRequest {
    const message = createBaseListWfMetricsRequest();
    message.wfSpec = (object.wfSpec !== undefined && object.wfSpec !== null)
      ? WfSpecId.fromPartial(object.wfSpec)
      : undefined;
    message.windowStart = object.windowStart ?? undefined;
    message.windowEnd = object.windowEnd ?? undefined;
    return message;
  },
};

function createBaseListTaskMetricsRequest(): ListTaskMetricsRequest {
  return { taskDef: undefined, windowStart: undefined, windowEnd: undefined };
}

export const ListTaskMetricsRequest = {
  encode(message: ListTaskMetricsRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.taskDef !== undefined) {
      TaskDefId.encode(message.taskDef, writer.uint32(10).fork()).ldelim();
    }
    if (message.windowStart !== undefined) {
      Timestamp.encode(toTimestamp(message.windowStart), writer.uint32(18).fork()).ldelim();
    }
    if (message.windowEnd !== undefined) {
      Timestamp.encode(toTimestamp(message.windowEnd), writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListTaskMetricsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTaskMetricsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.taskDef = TaskDefId.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.windowStart = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.windowEnd = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTaskMetricsRequest {
    return {
      taskDef: isSet(object.taskDef) ? TaskDefId.fromJSON(object.taskDef) : undefined,
      windowStart: isSet(object.windowStart) ? globalThis.String(object.windowStart) : undefined,
      windowEnd: isSet(object.windowEnd) ? globalThis.String(object.windowEnd) : undefined,
    };
  },

  toJSON(message: ListTaskMetricsRequest): unknown {
    const obj: any = {};
    if (message.taskDef !== undefined) {
      obj.taskDef = TaskDefId.toJSON(message.taskDef);
    }
    if (message.windowStart !== undefined) {
      obj.windowStart = message.windowStart;
    }
    if (message.windowEnd !== undefined) {
      obj.windowEnd = message.windowEnd;
    }
    return obj;
  },

  create(base?: DeepPartial<ListTaskMetricsRequest>): ListTaskMetricsRequest {
    return ListTaskMetricsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListTaskMetricsRequest>): ListTaskMetricsRequest {
    const message = createBaseListTaskMetricsRequest();
    message.taskDef = (object.taskDef !== undefined && object.taskDef !== null)
      ? TaskDefId.fromPartial(object.taskDef)
      : undefined;
    message.windowStart = object.windowStart ?? undefined;
    message.windowEnd = object.windowEnd ?? undefined;
    return message;
  },
};

function createBaseMetricsList(): MetricsList {
  return { windows: [] };
}

export const MetricsList = {
  encode(message: MetricsList, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.windows) {
      MetricWindow.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MetricsList {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMetricsList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.windows.push(MetricWindow.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MetricsList {
    return {
      windows: globalThis.Array.isArray(object?.windows)
        ? object.windows.map((e: any) => MetricWindow.fromJSON(e))
        : [],
    };
  },

  toJSON(message: MetricsList): unknown {
    const obj: any = {};
    if (message.windows?.length) {
      obj.windows = message.windows.map((e) => MetricWindow.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<MetricsList>): MetricsList {
    return MetricsList.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MetricsList>): MetricsList {
    const message = createBaseMetricsList();
    message.windows = object.windows?.map((e) => MetricWindow.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(dateStr: string): Timestamp {
  const date = new globalThis.Date(dateStr);
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): string {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis).toISOString();
}

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
