/**
 * Probe backlog: java-surface members whose features DO change compiled
 * output but have no probe pair yet — visible, diffable debt (see
 * proposals/sdk-js-parity/wfsdk.md, Design 2, the rollout ratchet).
 *
 * conformance/probes.test.ts asserts the actually-unprobed set equals this
 * list EXACTLY. Landing a probe therefore forces deleting its line here in
 * the same PR, and the list can never silently grow: a brand-new Java member
 * is caught by the freshness check first and triaged deliberately.
 */
export const PROBE_BACKLOG: string[] = [
  'InlineLHStructBuilder#put',
  'InterruptHandler#withEventType',
  'LHExpression#and',
  'LHExpression#castTo',
  'LHExpression#castToBool',
  'LHExpression#castToBytes',
  'LHExpression#castToDouble',
  'LHExpression#castToInt',
  'LHExpression#castToStr',
  'LHExpression#castToWfRunId',
  'LHExpression#doesContain',
  'LHExpression#doesNotContain',
  'LHExpression#extend',
  'LHExpression#isEqualTo',
  'LHExpression#isGreaterThan',
  'LHExpression#isIn',
  'LHExpression#isLessThan',
  'LHExpression#isNotEqualTo',
  'LHExpression#isNotIn',
  'LHExpression#or',
  'LHExpression#pow',
  'LHExpression#removeIfPresent',
  'LHExpression#removeKey',
  'LHStructBuilder#put',
  'NodeOutput#get',
  'NodeOutput#jsonPath',
  'SpawnedThread#getThreadNumberVariable',
  'TaskNodeOutput#timeout',
  'TaskNodeOutput#withExponentialBackoff',
  'UserTaskOutput#withOnCancellationException',
  'WaitForThreadsNodeOutput#handleAnyFailureOnChild',
  'WaitForThreadsNodeOutput#handleErrorOnChild',
  'WaitForThreadsNodeOutput#handleExceptionOnChild',
  'WfRunVariable#asInherited',
  'WfRunVariable#get',
  'WfRunVariable#isGreaterThanEq',
  'WfRunVariable#isLessThanEq',
  'WfRunVariable#withAccessLevel',
  'Workflow#setDefaultTaskExponentialBackoffPolicy',
  'Workflow#setDefaultTaskRetries',
  'Workflow#setDefaultTaskTimeout',
  'Workflow#setParent',
  'Workflow#withDefaultThreadRetentionPolicy',
  'Workflow#withRetentionPolicy',
  'Workflow#withUpdateType',
  'WorkflowThread#add',
  'WorkflowThread#addVariable',
  'WorkflowThread#buildInlineStruct',
  'WorkflowThread#buildStruct',
  'WorkflowThread#cancelUserTaskRunAfterAssignment',
  'WorkflowThread#complete',
  'WorkflowThread#declareArray',
  'WorkflowThread#declareMap',
  'WorkflowThread#declareStruct',
  'WorkflowThread#divide',
  'WorkflowThread#extend',
  'WorkflowThread#multiply',
  'WorkflowThread#pow',
  'WorkflowThread#reassignUserTask',
  'WorkflowThread#removeIfPresent',
  'WorkflowThread#removeIndex',
  'WorkflowThread#removeKey',
  'WorkflowThread#scheduleReminderTaskOnAssignment',
  'WorkflowThread#subtract',
  'WorkflowThread#waitForAnyOf',
  'WorkflowThread#waitForFirstOf',
  'WorkflowThread#withRetentionPolicy',
]
