status = ERROR
name = InlineWorkflowExample
appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5p %c{1} - %m%n
rootLogger = INFO, console
