export { H1, type H1Props } from './H1'
export { H2, type H2Props } from './H2'
export { H3, type H3Props } from './H3'
export { H4, type H4Props } from './H4'
export { H5, type H5Props } from './H5'
