name: analysis
run-name: Code Analysis
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  server-dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17
      - name: Build
        run: ./gradlew server:installDist -x test
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: "server"
          path: "server"
          format: "HTML"
          out: "reports"
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: server report
          path: ${{github.workspace}}/reports
  sdk-java-dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17
      - name: Build
        run: ./gradlew sdk-java:build -x test
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: "sdk-java"
          path: "sdk-java"
          format: "HTML"
          out: "reports"
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: sdk-java report
          path: ${{github.workspace}}/reports
