name: analysis
run-name: Code Analysis
on:
  push:
    branches:
      - "**"

jobs:
  server-dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17
      - name: Build
        run: ./gradlew server:build -x test
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'server'
          path: '.'
          format: 'HTML'
          out: 'reports'
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: report
           path: ${{github.workspace}}/reports
  sdk-java-dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17
      - name: Build
        run: ./gradlew sdk-java:build -x test
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'sdk-java'
          path: '.'
          format: 'HTML'
          out: 'reports'
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: report
           path: ${{github.workspace}}/reports
