name: weekly-snapshot
run-name: Snapshot ${{ github.ref_name }}
on:
  schedule:
    - cron: "0 0 * * 5"

permissions:
      packages: write
      contents: write
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      snapshot-version: ${{ steps.extract.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Extract version
        id: extract
        working-directory: release-manager/scripts
        run: |
          version=$(python3 extract_version.py)
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Validate snapshot
        working-directory: release-manager/scripts
        env:
          VERSION: ${{ steps.extract.outputs.version }}
        run: python3 validate.py --type snapshot --version "$VERSION"

  publish-java-libraries:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Tests
        run: ./gradlew sdk-java:test test-utils:test test-utils-container:test

      - name: Publish Snapshot
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_PASSWORD }}
        run: >
          ./gradlew
          sdk-java:publishToSonatype
          test-utils:publishToSonatype
          test-utils-container:publishToSonatype
